### ISSUE TITLE
适用于中国大陆的cdnjs镜像库 Cdnjs mirror repository for mainland China

### ISSUE THREAD

**Issue by feizhuqwq** [cdnjs/packages#1011]
## 适用于中国大陆的cdnjs镜像服务，字节跳动静态资源公共库 [https://cdn.bytedance.com/](https://cdn.bytedance.com/)

底层CDN来自 阿里CDN（服务大陆的alikulun），金山CDN，白山CDN，华为CDN
阿里kulun : https://lf3-cdn-tos.bytecdntp.com/...
金山CDN : https://lf6-cdn-tos.bytecdntp.com/...
白山云CDN : https://lf9-cdn-tos.bytecdntp.com/...
华为云CDN : https://lf26-cdn-tos.bytecdntp.com/...

cdnjs mirroring service for mainland China, byte-hopping static resource public library [https://cdn.bytedance.com/](https://cdn.bytedance.com/)
The underlying CDN comes from Ali CDN (serving mainland alikulun), Jinshan CDN, Baishan CDN, Huawei CDN

Please do not close this lssues, I want mainland China users to be able to see this lssues

**Comment by MattIPv4** [comment]
Please do not spam across multiple repos, you've already posted in the cdnjs discussions.

**Comment by feizhuqwq** [comment]
Ok, thanks
