### ISSUE TITLE
Add: rollup

### ISSUE THREAD

**Issue by zhoukekestar** [cdnjs/packages#1012]
### Library name

rollup

### Library license

https://github.com/rollup/rollup/blob/master/LICENSE.md

### Library source

https://www.npmjs.com/package/rollup

**Comment by MattIPv4** [comment]
👋 Rollup is a Node CLI tool, not meant for use in the browser. cdnjs primarily acts as a host for libraries that will be used by websites. What exactly is the use-case for having this added to the CDN?

**Comment by zhoukekestar** [comment]
Rollup support browser runtime by: https://unpkg.com/rollup@2.67.2/dist/rollup.browser.js
We use it in a REPL playground or something like WebIDE.
