### ISSUE TITLE
Update: jqueryui to 1.13(.x)

### ISSUE THREAD

**Issue by Crwmy** [cdnjs/packages#1013]
### Library name

jqueryui

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/j/jqueryui.json

### Library source

https://github.com/jquery/jquery-ui

### Files to include

- jquery-ui.min.js

### Note
jQuery UI prior 1.13 has three XSS vulnerabilities that are considered high according to [Snyk](https://snyk.io/vuln/npm:jquery-ui?lh=1.12.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit).

**Comment by MattIPv4** [comment]
👋 As noted in #889, jQuery UI is not distributed in a way that cdnjs can pull in. We have asked their team to provide a distribution that we could use (git tags, or an NPM package).

**Comment by Crwmy** [comment]
@MattIPv4 thanks and sorry for the busywork. When I searched for jquery and 1.13 the issue didn't show up 😕
