### ISSUE TITLE
Update: autonumeric

### ISSUE THREAD

**Issue by wfjsw** [cdnjs/packages#1042]
### Library name

autonumeric

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/a/autonumeric.json

### Library source

https://www.npmjs.com/package/autonumeric

### Files to include

- dist/autoNumeric.min.js

**Comment by wfjsw** [comment]
@MattIPv4 It seems there are issues preventing it from publish the new config and versions. Could you please take a brief look?

**Comment by MattIPv4** [comment]
I triggered a manual update of the library, and it appears to have gone through now :) https://github.com/cdnjs/logs/commit/8130a284deac521233f08aff571bd647eaf35f97

**Comment by wfjsw** [comment]
https://cdnjs.com/libraries/autonumeric missing an `npm package` link looks concerning btw.

**Comment by MattIPv4** [comment]
That's likely just caching -- https://api.cdnjs.com/libraries/autonumeric is still indicating that the library is using git, but the raw data is now reflecting npm: https://metadata.speedcdnjs.com/packages/autonumeric
