### ISSUE TITLE
Update: jQuery UI 1.13.1

### ISSUE THREAD

**Issue by Machou** [cdnjs/packages#1057]
### Library name

jqueryui

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/j/jqueryui.json

### Library source

https://github.com/jquery/jquery-ui

### Files to include

jquery-ui.min.js
jquery-ui.min.css
jquery-ui.structure.min.css
jquery-ui.theme.min.css
themes/base/jquery-ui.min.css
themes/base/theme.min.css
themes/black-tie/jquery-ui.min.css
themes/black-tie/theme.min.css
themes/blitzer/jquery-ui.min.css
themes/blitzer/theme.min.css
themes/cupertino/jquery-ui.min.css
themes/cupertino/theme.min.css
themes/dark-hive/jquery-ui.min.css
themes/dark-hive/theme.min.css
themes/dot-luv/jquery-ui.min.css
themes/dot-luv/theme.min.css
themes/eggplant/jquery-ui.min.css
themes/eggplant/theme.min.css
themes/excite-bike/jquery-ui.min.css
themes/excite-bike/theme.min.css
themes/flick/jquery-ui.min.css
themes/flick/theme.min.css
themes/hot-sneaks/jquery-ui.min.css
themes/hot-sneaks/theme.min.css
themes/humanity/jquery-ui.min.css
themes/humanity/theme.min.css
themes/le-frog/jquery-ui.min.css
themes/le-frog/theme.min.css
themes/mint-choc/jquery-ui.min.css
themes/mint-choc/theme.min.css
themes/overcast/jquery-ui.min.css
themes/overcast/theme.min.css
themes/pepper-grinder/jquery-ui.min.css
themes/pepper-grinder/theme.min.css
themes/redmond/jquery-ui.min.css
themes/redmond/theme.min.css
themes/smoothness/jquery-ui.min.css
themes/smoothness/theme.min.css
themes/south-street/jquery-ui.min.css
themes/south-street/theme.min.css
themes/start/jquery-ui.min.css
themes/start/theme.min.css
themes/sunny/jquery-ui.min.css
themes/sunny/theme.min.css
themes/swanky-purse/jquery-ui.min.css
themes/swanky-purse/theme.min.css
themes/trontastic/jquery-ui.min.css
themes/trontastic/theme.min.css
themes/ui-darkness/jquery-ui.min.css
themes/ui-darkness/theme.min.css
themes/ui-lightness/jquery-ui.min.css
themes/ui-lightness/theme.min.css
themes/vader/jquery-ui.min.css
themes/vader/theme.min.css

**Comment by MattIPv4** [comment]
👋 As noted in https://github.com/cdnjs/packages/issues/889, jQuery UI is not distributed in a way that cdnjs can pull in. We have asked their team to provide a distribution that we could use (git tags, or an NPM package).
