### ISSUE TITLE
Add: compressorjs

### ISSUE THREAD

**Issue by yeasherarafath** [cdnjs/packages#1085]
### Library name

compressorjs

### Library license

https://github.com/fengyuanchen/compressorjs/blob/main/LICENSE

### Library source

https://github.com/fengyuanchen/compressorjs

### Files to include

├── compressor.js
├── compressor.min.js
├── compressor.common.js
└── compressor.esm.js

**Comment by MattIPv4** [comment]
The latest version is already available on cdnjs: https://cdnjs.com/libraries/compressorjs
