### ISSUE TITLE
update version of openlayers

### ISSUE THREAD

**Issue by alansaviolobo** [cdnjs/packages#1097]
The OpenLayers library is available on cdnjs at [https://cdnjs.com/libraries/openlayers](https://cdnjs.com/libraries/openlayers)

However the latest version available is 4.6.5
The latest version available at [https://github.com/openlayers/openlayers/](https://github.com/openlayers/openlayers/) is 6.14.1

Requesting the latest version to be available on cdnjs

**Comment by alansaviolobo** [comment]
Does this need to be deployed? Asking because the latest version is still showing as 4.6.5

**Comment by MattIPv4** [comment]
The bot will take a while to process all the missing versions -- you can track the logs here: https://github.com/cdnjs/logs/tree/prod/packages/o/openlayers

**Comment by alansaviolobo** [comment]
The version dropdown at https://cdnjs.com/libraries/openlayers shows alot of -dev files but not the latest release files.

also, any reason why both these exist (as they are identical) ?
[openlayers](https://cdnjs.com/libraries/openlayers)
[ol3](https://cdnjs.com/libraries/ol3)

**Comment by MattIPv4** [comment]
I would suspect that the bot is still working through the backlog of versions, given it still seems to be committing new versions in logs all the time -- the `ol` package has almost 2k versions it needs to pull in.

As for why there are two packages on cdnjs, unsure off the top of my head, there might be some context in the PRs that added/updated them last.
