### ISSUE TITLE
update version of jqueryui

### ISSUE THREAD

**Issue by taicomjp** [cdnjs/packages#1099]
The jqueryuilibrary is available on cdnjs at https://cdnjs.com/libraries/jqueryui

However the latest version available is 1.13.1
The latest version available at https://github.com/openlayers/jqueryui/ is 1.12.1

Requesting the latest version to be available on cdnjs

**Comment by MattIPv4** [comment]
👋 As noted in https://github.com/cdnjs/packages/issues/889, jQuery UI is not distributed in a way that cdnjs can pull in. We have asked their team to provide a distribution that we could use (git tags, or an NPM package).
