### ISSUE TITLE
Update: awesomplete

### ISSUE THREAD

**Issue by Lofesa** [cdnjs/packages#1119]
### Library name

awesomplete

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/a/awesomplete.json

### Library source

https://github.com/LeaVerou/awesomplete

### Files to include

https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.min.js.map

This file is NOT in cdnjs.com and throw errors when awesomplete.min.js is used with a 404 error status.

**Comment by Lofesa** [comment]
Maybe a new line must be added belows line 23 in the json file
"awesomplete*.map"

**Comment by Lofesa** [comment]
Hi @MattIPv4 
Thks for the PR
I see now css maps added, but not the js map., somethings is wrong.

**Comment by MattIPv4** [comment]
Nothing has changed at all, so if you're seeing the CSS maps, they were always there.

A new version of the library will need to be published before the updated config takes effect.

**Comment by Lofesa** [comment]
Hi @MattIPv4 
Can't be updated in other way other than a new release?
The github repo seems to be dead. No changes in the last 2 years, unless the readme.md.
Openend a issue, but no response at all....

**Comment by MattIPv4** [comment]
Unfortunately not, updating an existing version of a library would break its integrity on the CDN.

Fwiw, map files for JS/CSS aren't required and you can always pull them down yourself from the source if you do need to explore them.
