### ISSUE TITLE
Latest version of marked not updated

### ISSUE THREAD

**Issue by wlnirvana** [cdnjs/packages#1122]
cdnjs currently hosts [marked up to 4.0.2](https://github.com/cdnjs/cdnjs/tree/46c5447bc8e0aa9ba5e486bb03c9c297909d683a/ajax/libs/marked), which is already over 5 months old. Ten newer versions have been released since then.

However, the [package config json](https://github.com/cdnjs/packages/blob/270ec08c67680b03238b36bd32f095752ec2816d/packages/m/marked.json) seems fine. Is there anything wrong causing marked not being updated automatically?

**Comment by MattIPv4** [comment]
The package.json is looking specifically for a file named `marked.js`, but the repo appears to have renamed the files. Just needs the filemap to be updated to look for `*.@(cjs|js)`

**Comment by wlnirvana** [comment]
I see. I've created PR #1124 to address this issue.

**Comment by MattIPv4** [comment]
https://github.com/cdnjs/packages/commit/deb0fa82048e79a7619619e6b02ca0f7ef59b5e3
