### ISSUE TITLE
Add: generate-schema

### ISSUE THREAD

**Issue by kkolur** [cdnjs/packages#1140]
### Library name

generate-schema

### Library license

https://github.com/nijikokun/generate-schema/blob/master/LICENSE

### Library source

https://www.npmjs.com/package/generate-schema

### Files to include

- src/index.js

**Comment by MattIPv4** [comment]
👋 This library makes use of Node.js `require` calls that won't work in the browser. For us to ship a library on the CDN that will work on the web, the library needs to be distributed with a version that will work on the web.

**Comment by MattIPv4** [comment]
No progress, closing.
