### ISSUE TITLE
Add: noVnc library

### ISSUE THREAD

**Issue by magicLian** [cdnjs/packages#1150]
### Library name

noVnc

### Library license

https://github.com/novnc/noVNC/blob/master/LICENSE.txt

### Library source

https://github.com/novnc/noVNC

### Files to include

too much to write

**Comment by MattIPv4** [comment]
👋 This library (https://www.npmjs.com/package/@novnc/novnc) makes use of `require` and `exports` calls for Node.js, which will not work in a browser.

Please point me to the browser-compatible library if there is one, and we can add that.

**Comment by MattIPv4** [comment]
No progress, closing.
