### ISSUE TITLE
Update: USWDS

### ISSUE THREAD

**Issue by joeliir** [cdnjs/packages#1155]
### Library name

uswds

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/u/uswds.json

### Library source

https://github.com/uswds/uswds

### Files to include

**/!(*.md|*.scss)

**Comment by MattIPv4** [comment]
👋 cdnjs already has the latest version of this library that is published on NPM - 2.13.3:

- https://cdnjs.com/libraries/uswds
- https://www.npmjs.com/package/uswds

We also have the 3.0.0 beta versions that are available on NPM, as this library is configured to pull all versions available on NPM.

**Comment by joeliir** [comment]
It appears that the namespace has changed with the new version from "uswds" to "@uswds/uswds"  https://github.com/uswds/uswds/releases/tag/v3.0.0-beta.4 so that's why it isn't getting picked up.
