### ISSUE TITLE
need to add library DOMParser()

### ISSUE THREAD

**Issue by AwaisBinKaleem** [cdnjs/packages#1165]
i want to parse external xml file in reactjs but there is no way to use this class there.
i think there is not any other package to parse xlm that wou't be better than DOMParser().
so we need this package to be available on NPM or CDN.

**Comment by MattIPv4** [comment]
Doing a search on cdnjs indicates we already have an XML parser library: https://cdnjs.com/libraries?q=xml / https://cdnjs.com/libraries/fast-xml-parser

If this isn't what you want, please fill out the library request template properly with the library you wish to have added to cdnjs: https://github.com/cdnjs/packages/issues/new/choose
