### ISSUE TITLE
Add: butterfly-extsrc

### ISSUE THREAD

**Issue by jerryc127** [cdnjs/packages#1167]
### Library name

butterfly-extsrc

### Library license

https://github.com/jerryc127/butterfly-plugins/blob/main/butterfly-extsrc/LICENSE

### Library source

https://www.npmjs.com/package/butterfly-extsrc

### Files to include

- dist/* all js
- ShareJS/dist/* - css/js/eot/svg/ttf/woff
- MetingJS/dist/* - Meting.min.js

**Comment by jerryc127** [comment]
why still not find in cdnjs?
- ShareJS/dist/*
- MetingJS/dist/*

**Comment by MattIPv4** [comment]
It's all available: https://cdnjs.com/libraries/butterfly-extsrc
