### ISSUE TITLE
Add: xmldom

### ISSUE THREAD

**Issue by AwaisBinKaleem** [cdnjs/packages#1172]
### Library name

xmldom/xmldom

### Library license

https://github.com/xmldom/xmldom/blob/master/LICENSE

### Library source

https://www.npmjs.com/package/@xmldom/xmldom

### Files to include

- [conventions.js](https://github.com/xmldom/xmldom/blob/master/lib/conventions.js)
- [dom-parser.js](https://github.com/xmldom/xmldom/blob/master/lib/dom-parser.js)
- [dom.js](https://github.com/xmldom/xmldom/blob/master/lib/dom.js)
- [entities.js](https://github.com/xmldom/xmldom/blob/master/lib/entities.js)
- [index.js](https://github.com/xmldom/xmldom/blob/master/lib/index.js)
- [sax.js](https://github.com/xmldom/xmldom/blob/master/lib/sax.js)

**Comment by MattIPv4** [comment]
👋 This library makes use of Node.js `require` calls to operate, which will not work in a browser context. For a library to work in a browser, it needs to be pre-bundled.

Please let us know if there is a different browser target package we should be using.

**Comment by MattIPv4** [comment]
No progress, closing.
