### ISSUE TITLE
Add: UAParser.js v0.7.28-gpu-experimental

### ISSUE THREAD

**Issue by yeasherarafath** [cdnjs/packages#1180]
### Library name

UAParser

### Library JSON file

https://github.com/faisalman/ua-parser-js/blob/master/package.json

### Library source

https://faisalman.github.io/ua-parser-js/js/ua-parser.js

### Files to include

- ua-parser.js

**Comment by MattIPv4** [comment]
👋 The version you're requesting doesn't exist: https://www.npmjs.com/package/ua-parser-js

We can only add versions that are published.

**Comment by MattIPv4** [comment]
No progress, closing.
