### ISSUE TITLE
Add: idb

### ISSUE THREAD

**Issue by ChlodAlejandro** [cdnjs/packages#1187]
### Library name

idb

### Library license

https://github.com/jakearchibald/idb/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/idb

### Files to include

- build/umd.js

**Comment by MattIPv4** [comment]
👋 This library makes use of Node.js require calls to operate, which will not work in a browser context. For a library to work in a browser, it needs to be pre-bundled.

Please let us know if there is a different browser target package we should be using.

**Comment by MattIPv4** [comment]
No progress, closing.
