### ISSUE TITLE
Update: jquery-validation-unobtrusive

### ISSUE THREAD

**Issue by mkArtakMSFT** [cdnjs/packages#1246]
### Library name

jquery-validation-unobtrusive

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/j/jquery-validation-unobtrusive.json

### Library source

https://www.npmjs.com/package/jquery-validation-unobtrusive

### Files to include

My request is somewhat unique. The set of files in the library is correct.

The problem is that in v 4.0, the license for the library has been updated to MIT: https://github.com/aspnet/jquery-validation-unobtrusive/blob/main/LICENSE.txt
However, cdnjs picked up only package version update and not the license change. It would be great to get that fixed too.

**Comment by MattIPv4** [comment]
#1247

**Comment by mkArtakMSFT** [comment]
Thanks @MattIPv4. Glad that you're doing better now 👍 
How long do you think this change will show up on cdnjs?
I still see Apache license on the website:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/34246760/181801633-fd4a9302-8924-4f49-a1f3-add547385784.png">

**Comment by MattIPv4** [comment]
I believe we'll need a new version to be released for the metadata in the KV store to be updated. Once that happens though, should be pretty immediate (sans any caching).

**Comment by mkArtakMSFT** [comment]
Do you mean this change requires a new release of the jquery-validation-unobtrusive package (> v4.0.0) to npmjs?

**Comment by MattIPv4** [comment]
Indeed, the auto-update logic behind cdnjs only writes changes to KV when a new version gets processed.

**Comment by mkArtakMSFT** [comment]
Understood. Well, will let this be for time being then as it seems this will now get resolved organically after the next release. Thanks again for your help
