### ISSUE TITLE
Add: consultar-cnpj

### ISSUE THREAD

**Issue by augustodelucena** [cdnjs/packages#1254]
### Library name

consultar-cnpj

### Library license

https://github.com/cnpj-ws/consultar-cnpj

### Library source

https://www.npmjs.com/package/consultar-cnpj

### Files to include

https://github.com/cnpj-ws/consultar-cnpj/blob/main/src/index.js

**Comment by MattIPv4** [comment]
👋 This library makes use of Node.js require calls to operate, which will not work in a browser context. For a library to work in a browser, it needs to be pre-bundled.

Please let us know if there is a different browser target package we should be using.

**Comment by augustodelucena** [comment]
Hey Matt, I have found another way to work this around!
