### ISSUE TITLE
Add: three

### ISSUE THREAD

**Issue by GarveySun** [cdnjs/packages#1264]
### Library name

three

### Library license

https://github.com/mrdoob/three.js/blob/dev/LICENSE

### Library source

https://www.npmjs.com/package/three

### Files to include

- build/three.js
- build/three.min.js
- build/three.module.js

**Comment by MattIPv4** [comment]
Three.js is already available on cdnjs: https://cdnjs.com/libraries/three.js

Please file an update request if we're missing versions that you require.
