### ISSUE TITLE
Update: three

### ISSUE THREAD

**Issue by GarveySun** [cdnjs/packages#1265]
### Library name

three

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/t/three.js.json

### Library source

https://www.npmjs.com/package/three

### Files to include

- build/three.js
- build/three.min.js
- build/three.module.js

**Comment by GarveySun** [comment]
In fact, three.js on npm has stopped updating since six years ago, and it is now renamed as three.
maybe the /packages/t/three.json  file should be added instead update three.js.json.

**Comment by Hoooxz** [comment]
🙋‍♂️
