### ISSUE TITLE
Add: pyodide

### ISSUE THREAD

**Issue by harrypotterIUP** [cdnjs/packages#1267]
### Library name

pyodide

### Library license

https://github.com/pyodide/pyodide/blob/main/LICENSE

### Library source

https://github.com/pyodide/pyodide

### Files to include

Everything from inside the `pyodide-build-*.tar.bz2` archive of each GitHub release

**Comment by MattIPv4** [comment]
👀 We cannot pull files from GitHub releases, we either need the files in a tagged git repo, or published on NPM. I see this package has an NPM version, does this contain the files required?

**Comment by harrypotterIUP** [comment]
@MattIPv4 I apologize. I must have overlooked that GitHub releases doesn't work. Yes, the NPM package works, too.
