### ISSUE TITLE
Add: hexo-theme-volantis

### ISSUE THREAD

**Issue by MHuiG** [cdnjs/packages#1278]
### Library name

hexo-theme-volantis

### Library license

https://github.com/volantis-x/hexo-theme-volantis/blob/dev/LICENSE

### Library source

https://www.npmjs.com/package/hexo-theme-volantis

### Files to include

- source/**/*.css
- source/**/*.js

**Comment by MattIPv4** [comment]
👋 There are no `.css` files within the [`source` directory](https://www.digitalocean.com/community/tools/glob#?comments=true&glob=source%2F%2A%2A%2F%2A.css&matches=true&tests=%2F%2F%20Imported%20from%20hexo-theme-volantis%20NPM%20package&tests=LICENSE&tests=layout%2F_partial%2Fscripts%2F_ctrl.ejs&tests=layout%2F_pre.ejs&tests=layout%2F_widget%2F_pre.ejs&tests=layout%2F404.ejs&tests=layout%2F_plugins%2Fpjax%2Fanimate.ejs&tests=layout%2F_partial%2Farchive.ejs&tests=layout%2Farchive.ejs&tests=layout%2F_meta%2Fartalkcount.ejs&tests=layout%2F_partial%2Farticle.ejs&tests=layout%2F_meta%2Fauthor.ejs&tests=layout%2F_partial%2F_cover%2Fblank.ejs&tests=layout%2F_widget%2Fblogger.ejs&tests=layout%2F_partial%2Fcategories.ejs&tests=layout%2F_meta%2Fcategory.ejs&tests=layout%2F_widget%2Fcategory.ejs&tests=layout%2Fcategory.ejs&tests=layout%2F_partial%2Fscripts%2F_ctrl%2FcdnCtrl.ejs&tests=layout%2F_partial%2Fscripts%2Fcontent-visibility-scroll-fix.ejs&tests=layout%2F_widget%2Fcopyright.ejs&tests=layout%2F_meta%2Fcounter.ejs&tests=layout%2F_partial%2Fcover.ejs&tests=layout%2F_partial%2Fscripts%2F_ctrl%2FcoverCtrl.ejs&tests=layout%2F_meta%2Fdate.ejs&tests=layout%2F_partial%2F_cover%2Fdock.ejs&tests=layout%2Fdocs.ejs&tests=layout%2F_partial%2F_cover%2Ffeatured.ejs&tests=layout%2F_partial%2F_cover%2Ffocus.ejs&tests=layout%2F_partial%2Ffooter.ejs&tests=layout%2Ffriends.ejs&tests=layout%2F_partial%2Fscripts%2Fglobal.ejs&tests=layout%2F_widget%2Fgrid.ejs&tests=layout%2F_widget%2Fgroup.ejs&tests=layout%2F_partial%2Fhead.ejs&tests=layout%2F_partial%2Fheader.ejs&tests=layout%2F_widget%2Fheader.ejs&tests=layout%2F_partial%2Fscripts%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Fartitalk%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Fbbtalk%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Ffcircle%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Fgitter%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Findent%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Fkatex%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Fmathjax%2Findex.ejs&tests=layout%2F_plugins%2F_page_plugins%2Fsnackbar%2Findex.ejs&tests=layout%2F_plugins%2Fchat%2Findex.ejs&tests=layout%2F_plugins%2Fcomments%2Findex.ejs&tests=layout%2F_plugins%2Fpjax%2Findex.ejs&tests=layout%2Findex.ejs&tests=layout%2F_widget%2Flastupdate.ejs&tests=layout%2F_partial%2F_cover%2Flayout.ejs&tests=layout%2F_plugins%2Faplayer%2Flayout.ejs&tests=layout%2F_plugins%2Frightmenu%2Flayout.ejs&tests=layout%2F_plugins%2Frightmenus%2Flayout.ejs&tests=layout%2F_plugins%2Fshare%2Flayout.ejs&tests=layout%2Flayout.ejs&tests=layout%2F_plugins%2Fanalytics%2FLCCounter.ejs&tests=layout%2F_widget%2Flist.ejs&tests=layout%2Flist.ejs&tests=layout%2F_widget%2Fload.ejs&tests=layout%2F_partial%2Fmeta.ejs&tests=layout%2F_meta%2Fmusic.ejs&tests=layout%2F_widget%2Fmusic.ejs&tests=layout%2F_widget%2Fpage.ejs&tests=layout%2Fpage.ejs&tests=layout%2F_plugins%2Fpjax%2Fpdata.ejs&tests=layout%2F_partial%2Fpost.ejs&tests=layout%2Fpost.ejs&tests=layout%2F_widget%2Fqrcode.ejs&tests=layout%2F_widget%2Freferences.ejs&tests=layout%2F_widget%2Frelated_posts.ejs&tests=layout%2F_plugins%2Fanalytics%2Fscript.ejs&tests=layout%2F_plugins%2Faplayer%2Fscript.ejs&tests=layout%2F_plugins%2Fchat%2Fgitter%2Fscript.ejs&tests=layout%2F_plugins%2Fchat%2Ftidio%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fartalk%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fbeaudar%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fdiscuss%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fdisqus%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fdisqusjs%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fgiscus%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fgitalk%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fhashover%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fisso%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Flivere%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Ftwikoo%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Futterances%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fvssue%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fwaline%2Fscript.ejs&tests=layout%2F_plugins%2Fcomments%2Fz-custom%2Fscript.ejs&tests=layout%2F_plugins%2Fdarkmode%2Fscript.ejs&tests=layout%2F_plugins%2Fend-of-support%2Fscript.ejs&tests=layout%2F_plugins%2Fgithub-api%2Fscript.ejs&tests=layout%2F_plugins%2Fhighlight%2Fhighlightjs%2Fscript.ejs&tests=layout%2F_plugins%2Fhighlight%2Fprismjs%2Fscript.ejs&tests=layout%2F_plugins%2Fhighlight%2Fscript.ejs&tests=layout%2F_plugins%2Flazyload%2Fscript.ejs&tests=layout%2F_plugins%2Fnodewaves%2Fscript.ejs&tests=layout%2F_plugins%2Fparallax%2Fscript.ejs&tests=layout%2F_plugins%2Fpreload%2Fscript.ejs&tests=layout%2F_plugins%2Fscrollreveal%2Fscript.ejs&tests=layout%2F_plugins%2Fsearch%2Fscript.ejs&tests=layout%2F_plugins%2Fslow-network%2Fscript.ejs&tests=layout%2F_plugins%2Fswiper%2Fscript.ejs&tests=layout%2F_partial%2F_cover%2Fsearch.ejs&tests=layout%2F_meta%2Fshare.ejs&tests=layout%2F_partial%2Fside.ejs&tests=layout%2Ftag.ejs&tests=layout%2F_widget%2Ftagcloud.ejs&tests=layout%2F_meta%2Ftags.ejs&tests=layout%2F_widget%2Ftext.ejs&tests=layout%2F_meta%2Fthumbnail.ejs&tests=layout%2F_partial%2Fscripts%2Ftoc.ejs&tests=layout%2F_widget%2Ftoc.ejs&tests=layout%2F_meta%2Fupdated.ejs&tests=layout%2F_meta%2Fwalinecount.ejs&tests=layout%2F_widget%2Fwebinfo.ejs&tests=layout%2F_meta%2Fwordcount.ejs&tests=source%2Fjs%2Fplugins%2Faplayer.js&tests=source%2Fjs%2Fapp.js&tests=scripts%2Fhelpers%2Fhead%2FautoCanonical.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Fblogposting.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Fbreadcrumblist.js&tests=scripts%2Ftags%2Fbtn.js&tests=scripts%2Ftags%2Fbtns.js&tests=scripts%2Fevents%2Flib%2Fcheck-configuration.js&tests=scripts%2Fevents%2Flib%2Fcheck-environment.js&tests=scripts%2Ftags%2Fcheckbox.js&tests=scripts%2Fevents%2Flib%2Fconfig.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Fconfig.js&tests=scripts%2Ffilters%2Fcontent-visibility.js&tests=scripts%2Ftags%2Fcontributors.js&tests=source%2Fjs%2Fplugins%2Ftags%2Fcontributors.js&tests=scripts%2Fhelpers%2Fcustom-files.js&tests=scripts%2Ftags%2Fdropmenu.js&tests=scripts%2Ftags%2Ffancybox.js&tests=scripts%2Fhelpers%2Ffirst-style.js&tests=scripts%2Ftags%2Ffolding.js&tests=scripts%2Ftags%2Fframe.js&tests=scripts%2Ftags%2Ffriends.js&tests=source%2Fjs%2Fplugins%2Ftags%2Ffriends.js&tests=scripts%2Fhelpers%2Fhead%2Fgenerate_preload_fontfamily.js&tests=scripts%2Fhelpers%2Fhead%2Fgenerate_seo.js&tests=scripts%2Fhelpers%2Fhead%2Fgenerate_title__keywords__description.js&tests=scripts%2Ftags%2Fghcard.js&tests=source%2Fjs%2Fsearch%2Fhexo.js&tests=scripts%2Ftags%2Fimage.js&tests=scripts%2Ffilters%2Fimg.js&tests=scripts%2Fevents%2Findex.js&tests=scripts%2Fhelpers%2Fstructured-data%2Findex.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Findex.js&tests=scripts%2Ftags%2Finline-labels.js&tests=scripts%2Ftags%2Flink.js&tests=scripts%2Ftags%2Fmd.js&tests=scripts%2Ftags%2Fmedia.js&tests=scripts%2Ftags%2Fnote.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Forganization.js&tests=scripts%2Ftags%2Fpandown.js&tests=source%2Fjs%2Fplugins%2Fparallax.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Fperson.js&tests=scripts%2Fhelpers%2Frelated-posts.js&tests=scripts%2Fevents%2Flib%2Frender-stylus.js&tests=scripts%2Ffilters%2Freplace.js&tests=scripts%2Fhelpers%2Frevisioned.js&tests=source%2Fjs%2Fplugins%2FrightMenu.js&tests=source%2Fjs%2Fplugins%2FrightMenus.js&tests=scripts%2Ftags%2Fsite.js&tests=source%2Fjs%2Fplugins%2Ftags%2Fsites.js&tests=scripts%2Ftags%2Fspan.js&tests=scripts%2Fevents%2Flib%2Fstellar-tag-utils.js&tests=scripts%2Ftags%2Fswiper.js&tests=scripts%2Ftags%2Ftable.js&tests=scripts%2Ftags%2Ftabs.js&tests=scripts%2Ftags%2Ftimeline.js&tests=scripts%2Fhelpers%2Fstructured-data%2Flib%2Fwebsite.js&tests=scripts%2Ffilters%2Fz-lazyload.js&tests=package.json&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ftag.json&tests=CHANGELOG.md&tests=README.md&tests=source%2Fcss%2F_defines%2FReadme.md&tests=source%2Fcss%2F_style%2F_tag-plugins%2FReadme.md&tests=source%2Fcss%2FReadme.md&tests=source%2Fcss%2F_style%2F_plugins%2Faplayer.styl&tests=source%2Fcss%2F_style%2F_layout%2Farchive.styl&tests=source%2Fcss%2F_style%2F_layout%2Farticle.styl&tests=source%2Fcss%2F_defines%2FAutoPrefixCSS.styl&tests=source%2Fcss%2F_first%2Fbase_first.styl&tests=source%2Fcss%2F_style%2F_base%2Fbase.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fbtns.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fcheckbox.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fhighlightjs%2Fclipboard.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fprismjs%2Fclipboard.styl&tests=source%2Fcss%2F_defines%2Fcolor.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fhighlightjs%2Fcolor.styl&tests=source%2Fcss%2F_first%2Fcover_first.styl&tests=source%2Fcss%2F_style%2F_plugins%2Fcursor.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_dark%2Fdark_async.styl&tests=source%2Fcss%2F_first%2Fdark_first.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_dark%2Fdark_plugins.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fdropmenu.styl&tests=source%2Fcss%2F_defines%2Feffect.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ffancybox.styl&tests=source%2Fcss%2Ffirst.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ffolding.styl&tests=source%2Fcss%2F_style%2F_plugins%2Ffontcolor.styl&tests=source%2Fcss%2F_style%2F_base%2Ffontfamily_async.styl&tests=source%2Fcss%2F_first%2Ffontfamily_first.styl&tests=source%2Fcss%2F_defines%2Ffonts.styl&tests=source%2Fcss%2F_style%2F_layout%2Ffooter.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fframe.styl&tests=source%2Fcss%2F_style%2F_layout%2Ffriends-simpleuser.styl&tests=source%2Fcss%2F_style%2F_layout%2Ffriends-traditional.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ffriends.styl&tests=source%2Fcss%2F_defines%2Ffunc.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fghcard.styl&tests=source%2Fcss%2F_style%2F_plugins%2Fgitalk.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fimage.styl&tests=source%2Fcss%2F_style%2F_layout%2Fimg.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fhighlightjs%2Findex.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Findex.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fprismjs%2Findex.styl&tests=source%2Fcss%2F_style%2F_plugins%2Findex.styl&tests=source%2Fcss%2F_style%2Findex.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fhighlightjs%2Flanguage.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_highlight%2Fprismjs%2Flanguage.styl&tests=source%2Fcss%2F_defines%2Flayout.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Flink.styl&tests=source%2Fcss%2F_style%2F_layout%2Floading.styl&tests=source%2Fcss%2F_style%2F_layout%2Fmain.styl&tests=source%2Fcss%2F_style%2F_plugins%2Fmathjax.styl&tests=source%2Fcss%2F_style%2F_layout%2Fmd.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fmedia.styl&tests=source%2Fcss%2F_style%2F_plugins%2Fmessage.styl&tests=source%2Fcss%2F_first%2Fnavbar_first.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fnote.styl&tests=source%2Fcss%2F_style%2F_layout%2Fpagination.styl&tests=source%2Fcss%2F_style%2F_plugins%2Fpjaxanimate.styl&tests=source%2Fcss%2F_style%2F_layout%2Fposts.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_rightmenu%2Freading.styl&tests=source%2Fcss%2F_style%2F_plugins%2F_rightmenu%2Frightmenu.styl&tests=source%2Fcss%2F_first%2Fsearch_first.styl&tests=source%2Fcss%2F_style%2F_layout%2Fsearch.styl&tests=source%2Fcss%2F_style%2F_layout%2Fsidebar.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fsites.styl&tests=source%2Fcss%2F_style%2F_layout%2Fsnackbar.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fspan.styl&tests=source%2Fcss%2Fstyle.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Fswiper.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ftable.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ftabs.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ftext.styl&tests=source%2Fcss%2F_style%2F_tag-plugins%2Ftimeline.styl&tests=source%2Fcss%2F_style%2F_layout%2Ftoc.styl&tests=source%2Fcss%2F_style%2F_layout%2Fvideo.styl&tests=_config.yml&tests=languages%2Fen.yml&tests=languages%2Fzh-CN.yml&tests=languages%2Fzh-TW.yml)?

**Comment by MHuiG** [comment]
👋 The previous version contained CSS files, yes there is no CSS file now, But, I'm not sure if there will be in the future.

E.g: hexo-theme-volantis@5.0.0-rc.1
https://cdn.jsdelivr.net/npm/hexo-theme-volantis@5.0.0-rc.1/source/css/

**Comment by MHuiG** [comment]
Can cdnjs collect previous version?

**Comment by MattIPv4** [comment]
Ah, thanks for linking that.

And yes, we pull in the last 10 versions iirc.

**Comment by MHuiG** [comment]
If so, we only need to import the js file.

- source/js/**/*.js
