### ISSUE TITLE
Add: volantis-static

### ISSUE THREAD

**Issue by MHuiG** [cdnjs/packages#1284]
### Library name

volantis-static

### Library license

https://github.com/volantis-x/volantis-static/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/volantis-static

### Files to include

- libs/**/*.js
- libs/**/*.css

**Comment by MattIPv4** [comment]
👋 This seems to just be a collection of other libs -- I don't see the value in duplicating that content on the CDN.

Are there specific files within this project that are unique to this project that we should be pulling in?

**Comment by MHuiG** [comment]
👋 Here are some unique files:
- /libs/fcircle/fcircle.css
- /libs/fcircle/fcircle.js
- /libs/flying-pages/flying-pages.min.js
- /libs/comment_typing/comment_typing.js

**Comment by MattIPv4** [comment]
What is different about `/libs/flying-pages/flying-pages.min.js` compared to #1279? This seems to just be an aggregation of other packages?

**Comment by MHuiG** [comment]
#1279 is a version three years ago, here is the latest version

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/190880014-ba6ec5df-de9f-4a29-b02d-35680dad14c4.png)

**Comment by MattIPv4** [comment]
Why is the latest version being distributed here, as part of `volantis-static`, rather than as its own package?

I'm failing to understand how adding `volantis-static` is going to benefit the end user, as they won't know that it contains a newer version of `flying-pages` within it?

**Comment by MHuiG** [comment]
Can #1328 be changed to github tag release?

Library source: https://github.com/gijo-varghese/flying-pages/releases

If so there is no need to add flying-pages here

**Comment by MHuiG** [comment]
Here are some unique files:

/libs/fcircle/fcircle.css
/libs/fcircle/fcircle.js
/libs/comment_typing/comment_typing.js

**Comment by MattIPv4** [comment]
Please open issues to add those libraries themselves, rather than adding them via an unrelated aggregate package. Adding an aggregate package like this creates end-user confusion it's not known what libraries are contained within, and breaks library versioning.

**Comment by MHuiG** [comment]
However, these three files are only available here.

https://www.npmjs.com/search?q=fcircle
https://github.com/search?q=fcircle

Can't find them on npm or github

**Comment by MattIPv4** [comment]
This library definitely exists beyond just your aggregation of it: https://github.com/search?q=fcircle-pub&type=code

**Comment by MattIPv4** [comment]
Either way, arguing this back and forth isn't going to help. What you're requesting to be added here is very clearly an aggregation of other libraries, and that's not something I see as worth adding to cdnjs.

**Comment by MHuiG** [comment]
Why this aggregation library #1167 can exist in cdnjs, is it because it is not obvious enough?

- https://github.com/disjukr/activate-power-mode
- https://github.com/overtrue/share.js
- https://github.com/metowolf/MetingJS
- https://github.com/hustcc/ribbon.js
-  ....

https://github.com/jerryc127/butterfly-plugins/blob/main/butterfly-extsrc/src/activate-power-mode.js
https://github.com/disjukr/activate-power-mode/blob/gh-pages/dist/activate-power-mode.js
Modify is written here, but I found that it seems to just replace var with let and const
