### ISSUE TITLE
Add: PivotTable-Grouping.js    (fork)     

### ISSUE THREAD

**Issue by allanspielman** [cdnjs/packages#1301]
### Library name

pivottable-grouping

### Library license

https://github.com/nicolaskruchten/pivottable

### Library source

https://github.com/nicolaskruchten/pivottable/pull/1088/files

### Files to include

pivot.min.js
pivot.min.css

**Comments: I am not the creator of the fork . I wish ti have the forks version of pivottable.js  hosted on cdnjs  so I can use it in my code**

**Comment by allanspielman** [comment]
the reason for this is that right now, only the original version is on CLoudfare. I need the foprk that is pivottable grouping

![image](https://user-images.githubusercontent.com/110177972/185150840-eb379520-a7b7-46d1-8bcd-70ca6407ef80.png)

**Comment by MattIPv4** [comment]
👋 Unfortunately we're not really in a position to be able to just switch a library over to using an unverified fork. I'd recommend you encourage the maintainer of the original project to accept the contribution if you want to use it.
