### ISSUE TITLE
Add: Unfurl metadata scraper library to cdnjs

### ISSUE THREAD

**Issue by aMacDawg** [cdnjs/packages#1313]
### Library name

Unfurl

### Library license

https://github.com/jacktuck/unfurl/blob/master/LICENSE

### Library source

https://github.com/jacktuck/unfurl

### Files to include

- unfurl.min.js

**Comment by MattIPv4** [comment]
👋 I don't see a `unfurl.min.js` in this project when pulling it down from NPM?

There is a `dist/index.js` file, but this makes use of Node.js `require` calls and so will not work in a browser context.

Please let us know what files to include.

**Comment by aMacDawg** [comment]
thanks @MattIPv4 , realized later this was a node-dependent package and therefore not compatible. In any case, my own requirements for something like this have changed so I'm happy to close the ticket
