### ISSUE TITLE
Add: swagger2openapi

### ISSUE THREAD

**Issue by sandeepMannem** [cdnjs/packages#1316]
### Library name

swagger2openapi

### Library license

https://github.com/Mermade/oas-kit/blob/HEAD/LICENSE

### Library source

https://www.npmjs.com/package/swagger2openapi

### Files to include

-swagger2openapi.js
-oas-validate.js 
-statusCodes.js

**Comment by MattIPv4** [comment]
👋 `swagger2openapi.js` makes use of Node.js `require` calls, which won't work in a browser context. Please let us know what files we should include from the library for use on the web.

**Comment by MattIPv4** [comment]
No progress, closing.
