### ISSUE TITLE
Add: tinyduration

### ISSUE THREAD

**Issue by LordPachelbel** [cdnjs/packages#1326]
### Library name

tinyduration

### Library license

https://github.com/MelleB/tinyduration/blob/master/LICENSE.md

### Library source

https://github.com/MelleB/tinyduration

### Files to include

- `dist/index.d.ts`
- `dist/index.js`
- `dist/index.js.map`
- `dist/tsconfig.tsbuildinfo`

**Comment by MattIPv4** [comment]
👋 I wasn't able to include `dist/tsconfig.tsbuildinfo` here as that is not a file extension that cdnjs supports.
