### ISSUE TITLE
Update: Datatables 1.12.1

### ISSUE THREAD

**Issue by pickfire** [cdnjs/packages#1350]
### Library name

datatables

### Library JSON file

https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/datatables/package.json

### Library source

https://github.com/DataTables/DataTables

### Files to include

I didn't check all of it, but I noticed there is support for bootstrap 5 which wasn't there in current cdnjs version (1.10.21)

- css/dataTables.bootstrap5.min.css

**Comment by MattIPv4** [comment]
👋 This library is already available on cdnjs: https://cdnjs.com/libraries/datatables.net-bs5

**Comment by pickfire** [comment]
Ah, but it doesn't seemed to be discoverable from cdnjs.com search, I tried searching datatables 5 but it isn't in the first page of the results, there also doesn't seemed to be way to paginate it.

**Comment by MattIPv4** [comment]
All the datatables 5 packages show up when you search for datatables 5: https://cdnjs.com/libraries?q=datatables%205

**Comment by pickfire** [comment]
Ah, I didn't realized the results are different once you press `<enter>`, I only search `datatables 5` from https://cdnjs.com/.
