### ISSUE TITLE
Add: chartjs-adapter-date-fns

### ISSUE THREAD

**Issue by louise-davies** [cdnjs/packages#1354]
### Library name

chartjs-adapter-date-fns

### Library license

https://github.com/chartjs/chartjs-adapter-date-fns/blob/master/LICENSE.md

### Library source

https://www.npmjs.com/package/chartjs-adapter-date-fns

### Files to include

- chartjs-adapter-date-fns.min.js

**Comment by tamalchowdhury** [comment]
Added pull request #1357
