### ISSUE TITLE
Add: lasco

### ISSUE THREAD

**Issue by borisdamevin** [cdnjs/packages#1356]
### Library name

lasco

### Library license

https://github.com/magnesiumlabs/lasco/blob/main/LICENSE.md

### Library source

https://www.npmjs.com/package/lasco

### Files to include

/dist/lasco.css
/dist/lasco.min.css

**Comment by tamalchowdhury** [comment]
This library does not meet the required popularity, 800 monthly downloads on NPM or 200 stars on Github mentioned [here](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines)

Can you please clarify the numbers or the importance of including it on cdnjs?

**Comment by MattIPv4** [comment]
@tamalchowdhury This package does seem to meet the NPM requirement, and fwiw, wwe're generally pretty lax with it: https://npm-stat.com/charts.html?package=lasco&from=2022-08-01&to=2022-10-01

That being said, @borisdamevin the two dist files you mention here don't seem to exist in the NPM package from what I can tell?

```
> npm i lasco

added 23 packages, and audited 26 packages in 4s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> tree node_modules/lasco

node_modules/lasco
├── CHANGELOG.md
├── LICENSE.md
├── README.md
├── index.scss
├── package.json
├── src
│   ├── _config.scss
│   ├── _core-styles.scss
│   ├── _functions.scss
│   ├── _index.scss
│   ├── _mixins.scss
│   ├── _properties.scss
│   └── _variables.scss
└── styles.scss

1 directory, 13 files
```

**Comment by MattIPv4** [comment]
No progress, closing.
