### ISSUE TITLE
Add: carrierjs w/ npm auto-update

### ISSUE THREAD

**Issue by theritikchoure** [cdnjs/packages#1368]
### Library name

CarrierJs

### Library license

https://github.com/theritikchoure/carrierjs/blob/master/LICENSE.md

### Library source

https://www.npmjs.com/package/carrierjs

### Files to include

- carrier.js

**Comment by tamalchowdhury** [comment]
Hi @MattIPv4 not sure if this package meets the requirement, can you advise? https://npm-stat.com/charts.html?package=carrierjs

If so, let me add this to the repo. Thanks.

**Comment by MattIPv4** [comment]
Seems fine to add 👍

**Comment by MattIPv4** [comment]
#1369
