### ISSUE TITLE
Feature Request: Make the library adding feature semi-automated

### ISSUE THREAD

**Issue by tamalchowdhury** [cdnjs/packages#1371]
Hi team! I want to propose a new form so library vendors can enter all the required info and it will generate a `.json` file ready to review and add. By doing this, we can save valuable developer time from doing repetitive manual copy-pasting tasks.

## Motivation

I made a couple of additions to the library and found a few repetitive tasks. I follow previous JSON files as a template to add a new library. I have to copy a bunch of information like author's name, URL, and email from their GitHub profile. When I was adding the tags from #1369 that was a long list of npm tags to manually add:

![image](https://user-images.githubusercontent.com/7252898/196212971-07e903b0-9bb4-43ba-bd93-34e184ea8add.png)

All this can be generated using a client-side form and some of the info like tags can also be imported from the npm API. Saving project maintainer's valuable time.

## Proposed Solution

A standalone front-end app with a form to fill out the required information (similar to the current **add library** issue template). The user can enter the links, their name, URL, repo URL, tags, and extra information. The app will generate a `.json` file which then they can copy and paste to create an issue, or directly commit to the code themselves.

I can build a prototype if I get the green light.

**Comment by MattIPv4** [comment]
👀 I've been using https://github.com/MattIPv4/cdnjs-add-cli for a while now a CLI solution to this same problem. I'd be down to have a web UI built that does the same though (loading files will be a pain but is doable at least for NPM, see do.co/glob-tool).

**Comment by tamalchowdhury** [comment]
Thanks! Your CLI tool will be a good starting point for me to build out this page. Let's see what I can come up with.

**Comment by tamalchowdhury** [comment]
Hi @MattIPv4 I have an update.

I created a basic MVP for the form here https://github.com/tamalchowdhury/cdnjs-library-request-form (please check the hosted page on github pages for a quick [demo](https://tamalchowdhury.github.io/cdnjs-library-request-form/))

I used your CLI as a baseline for this project. Right now the output displays a formatted json.

Now I need your input/suggestions on the following:

- How can we also include the npm package directory? Is there a way to do this client-side or any affordable & secure ways to do these on the server side?
- Is this tool solves the overall problem we faced? Can you advise on this?

Thank you for your time. Have a great day.

**Comment by MattIPv4** [comment]
> How can we also include the npm package directory?

Take a look at how I did it over in https://github.com/do-community/glob-tool/blob/master/src/glob-tool/templates/package.vue, it should be possible to just load the NPM package directly in the browser so that you can let the user explore the package interactively, as my CLI tool does.

> Is this tool solves the overall problem we faced?

I think this has still got a ways to go before it solves the real problem here -- automating the collection of basic metadata, which your tool does currently, is the easy bit (but it also easy for a human to do quickly). The important bit that is yet to be solved for with this is providing a good UI for folks to create the auto-update config.

**Comment by tamalchowdhury** [comment]
Hi Matt, I am temporarily closing this issue since I haven't looked into it for a long time. I would like to revisit it again next time. Thanks for your input.
