### ISSUE TITLE
Add: fullcalendar@3.10.5

### ISSUE THREAD

**Issue by srmooney** [cdnjs/packages#1385]
### Library name

fullcalendar

### Library license

https://github.com/fullcalendar/fullcalendar/blob/master/LICENSE.txt

### Library source

https://github.com/fullcalendar/fullcalendar

### Files to include

- fullcalendar.min.css
- fullcalendar.min.js
- fullcalendar.print.min.css
- gcal.min.js
- locale-all.min.js
- locale/af.min.js
- locale/ar-dz.min.js
- locale/ar-kw.min.js
- locale/ar-ly.min.js
- locale/ar-ma.min.js
- locale/ar-sa.min.js
- locale/ar-tn.min.js
- locale/ar.min.js
- locale/be.min.js
- locale/bg.min.js
- locale/bs.min.js
- locale/ca.min.js
- locale/cs.min.js
- locale/da.min.js
- locale/de-at.min.js
- locale/de-ch.min.js
- locale/de.min.js
- locale/el.min.js
- locale/en-au.min.js
- locale/en-ca.min.js
- locale/en-gb.min.js
- locale/en-ie.min.js
- locale/en-nz.min.js
- locale/es-do.min.js
- locale/es-us.min.js
- locale/es.min.js
- locale/et.min.js
- locale/eu.min.js
- locale/fa.min.js
- locale/fi.min.js
- locale/fr-ca.min.js
- locale/fr-ch.min.js
- locale/fr.min.js
- locale/gl.min.js
- locale/he.min.js
- locale/hi.min.js
- locale/hr.min.js
- locale/hu.min.js
- locale/id.min.js
- locale/is.min.js
- locale/it.min.js
- locale/ja.min.js
- locale/ka.min.js
- locale/kk.min.js
- locale/ko.min.js
- locale/lb.min.js
- locale/lt.min.js
- locale/lv.min.js
- locale/mk.min.js
- locale/ms-my.min.js
- locale/ms.min.js
- locale/nb.min.js
- locale/nl-be.min.js
- locale/nl.min.js
- locale/nn.min.js
- locale/pl.min.js
- locale/pt-br.min.js
- locale/pt.min.js
- locale/ro.min.js
- locale/ru.min.js
- locale/sk.min.js
- locale/sl.min.js
- locale/sq.min.js
- locale/sr-cyrl.min.js
- locale/sr.min.js
- locale/sv.min.js
- locale/th.min.js
- locale/tr.min.js
- locale/uk.min.js
- locale/vi.min.js
- locale/zh-cn.min.js
- locale/zh-hk.min.js
- locale/zh-tw.min.js

**Comment by srmooney** [comment]
this library already exists, but is missing the 3.10.5 version

**Comment by MattIPv4** [comment]
👋 Unfortunately, it is not possible for us to pull in this version as it is rather old and the automation has moved past it.
