### ISSUE TITLE
Security: SRI wrong for https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js

### ISSUE THREAD

**Issue by sixcolors** [cdnjs/packages#1389]
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js SRI is listed as `sha512-CryKbMe7sjSCDPl18jtJI5DR5jtkUWxPXWaLCst6QjH8wxDexfRJic2WRmRXmstr2Y8SxDDWuBO6CQC6IE4KTA==` on https://cdnjs.com/libraries/moment.js in both the `Copy HTML Tag` and `Copy SRI Hash` link. The hash for the file is `sha512-+H4iLjY3JsKiF2V6N366in5IQHj2uEsGV7Pp/GRcm0fn76aPAk5V8xB6n8fQhhSonTqTXs/klFz4D0GIn6Br9g==`

This file may have been altered or the hash on the cdnjs website was somehow set incorrectly.

**Comment by MattIPv4** [comment]
Please see https://github.com/cdnjs/cdnjs/issues/14080 -- SRI mismatches are a known issue and have been escalated to Cloudflare previously. I'll bump it with them again.
