### ISSUE TITLE
Add: kraken-api

### ISSUE THREAD

**Issue by matnperes** [cdnjs/packages#1410]
### Library name

kraken-api

### Library license

https://github.com/nothingisdead/npm-kraken-api/blob/master/LICENSE.md

### Library source

https://www.npmjs.com/package/kraken-api

### Files to include

- kraken-api.min.js

**Comment by MattIPv4** [comment]
👋 This library does not include a bundled version meant for the web, the `kraken.js` file contained makes use of Node.js `require` calls that will not work on the web. Please let me know if there is a different file/source we should be looking at.

**Comment by MattIPv4** [comment]
No progress, closing.
