### ISSUE TITLE
Add: google-analytics-4-for-amp

### ISSUE THREAD

**Issue by irvin** [cdnjs/packages#1411]
### Library name

google-analytics-4-for-amp

### Library license

https://github.com/analytics-debugger/google-analytics-4-for-amp/blob/main/LICENSE

### Library source

https://github.com/analytics-debugger/google-analytics-4-for-amp/

### Files to include

- ga4.json

**Comment by MattIPv4** [comment]
👋 https://github.com/analytics-debugger/google-analytics-4-for-amp/ does not have any git tags that we can use to pull in versions. cdnjs has an auto-update mechanism that requires either a versioned NPM package, or a GitHub repository utilising git tags to track versions.

**Comment by irvin** [comment]
the author had ask if we can serve the different CORS header to every sites, due to the restriction of the AMP analytic library
(access-control-allow-origin: https://xxxx.xxx that is the origin of the request)

**Comment by MattIPv4** [comment]
No, it is not possible to change to CORS header for the CDN. It looks like the maintainer closed your issue asking for version tags, so I am going to close this issue as well.
