### ISSUE TITLE
Update: pyodide

### ISSUE THREAD

**Issue by sorcerer-ma** [cdnjs/packages#1412]
### Library name

pyodide

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/p/pyodide.json

### Library source

https://www.npmjs.com/package/pyodide

### Files to include

- distutils.tar
- pyodide.asm.data
- pyodide_py.tar
- pyodide_tblib-1.7.1-py3-none-any.whl
- repodata.json

**Comment by MattIPv4** [comment]
👋 cdnjs is not able to distribute `tar`, `whl` or `data` files. We can include the JSON file though if required. You can see the file extension list that cdnjs supports at https://api.cdnjs.com/whitelist

**Comment by MattIPv4** [comment]
No progress, closing.
