### ISSUE TITLE
Add: alt-lodash

### ISSUE THREAD

**Issue by PunitSoniME** [cdnjs/packages#1457]
### Library name

alt-lodash

### Library license

https://github.com/PunitSoniME/alt-lodash/blob/main/LICENSE

### Library source

https://www.github.com/punitsonime/alt-lodash

### Files to include

whole dist folder

**Comment by MattIPv4** [comment]
Just noting that I opted to not include the whole dist folder, as most of it appears to be folders of typing and some JS files that made use of Node.js `require` calls.
