### ISSUE TITLE
Add: Filerobot Image Editor

### ISSUE THREAD

**Issue by yeasherarafath** [cdnjs/packages#1464]
### Library name

Filerobot Image Editor

### Library license

https://github.com/scaleflex/filerobot-image-editor/blob/master/LICENSE

### Library source

https://github.com/scaleflex/filerobot-image-editor

### Files to include

- filerobot-image-editor.min.js

**Comment by MattIPv4** [comment]
👋 Where are you seeing the `filerobot-image-editor.min.js` that you are indicating should be included? Looking at the NPM package `filerobot-image-editor`, there is a `lib/index.js` file that makes use of NPM dependencies, so won't be compatible with the web.

**Comment by yeasherarafath** [comment]
**VanillaJS only**

https://github.com/scaleflex/filerobot-image-editor#cdn

**Comment by MattIPv4** [comment]
We cannot pull files from arbitrary URLs on cdnjs -- packages need to either be versioned in NPM or git. I don't see this CDN file available via either?
