### ISSUE TITLE
Add: ovh

### ISSUE THREAD

**Issue by martinez-hugo** [cdnjs/packages#1466]
### Library name

node-ovh

### Library license

https://github.com/ovh/node-ovh/blob/master/LICENSE

### Library source

https://github.com/ovh/node-ovh

### Files to include

- [ovh.es6.js](https://github.com/ovh/node-ovh/blob/master/lib/ovh.es6.js)
- [ovh.es5.js](https://github.com/ovh/node-ovh/blob/master/lib/ovh.es5.js)
- [handler-maker.js](https://github.com/ovh/node-ovh/blob/master/lib/handler-maker.js)
- [endpoints.js](https://github.com/ovh/node-ovh/blob/master/lib/endpoints.js)

**Comment by martinez-hugo** [comment]
PR #1472

**Comment by MattIPv4** [comment]
Closing per discussion in the PR, this library is not built for the web.
