### ISSUE TITLE
Add: Adobe Sign

### ISSUE THREAD

**Issue by vicbog11** [cdnjs/packages#1481]
### Library name

Adobe Sign

### Library license

https://github.com/adobe/acrobat-sign/blob/main/LICENSE.md

### Library source

https://github.com/adobe/acrobat-sign

### Files to include

acrobat-sign/sdks/AcrobatSign_JS_SDK/scr/index.js
acrobat-sign/sdks/AcrobatSign_REST_Samples

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING.md](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md) document.
