### ISSUE TITLE
Add: pitagon-sans

### ISSUE THREAD

**Issue by travistran1989** [cdnjs/packages#1490]
### Library name

pitagon-sans

### Library license

https://github.com/ThePitagon/pitagon-sans/blob/main/LICENSE.md

### Library source

https://github.com/ThePitagon/pitagon-sans

### Files to include

- dist/**

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING.md](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md) document.

The linked GitHub repository does have a tag, but looking at the files in the repo at that tag, I don't see anything that looks like files intended to be distributed: https://github.com/ThePitagon/pitagon-sans/tree/v1.0.1

**Comment by MattIPv4** [comment]
No progress, closing.
