### ISSUE TITLE
Use https links for homepage

### ISSUE THREAD

**Issue by imba-tjd** [cdnjs/packages#1491]
I suppose the more https the better.

For example:

![图片](https://user-images.githubusercontent.com/24759802/224461844-88b5ad2c-2bcf-436f-95f9-d00f3ff297be.png)

There are over 2000 links that are not https. An automation link-checking tool is needed.

**Comment by MattIPv4** [comment]
Thanks for opening this. I'm not sure it makes sense to require https on these links, as not all sites support it still (especially legacy/abandoned libraries). That being said, feel free to open a PR to update any links that do support https :)
