### ISSUE TITLE
Add: Apache Arrow

### ISSUE THREAD

**Issue by purnendumaity** [cdnjs/packages#1494]
### Library name

Apache Arrow

### Library license

https://github.com/apache/arrow/blob/main/LICENSE.txt

### Library source

https://github.com/apache/arrow

### Files to include

All JS files under below directory :
https://github.com/apache/arrow/tree/main/js/src

**Comment by MattIPv4** [comment]
👋 Many of these files appear to use Node.js `require` calls, which will not work on the web. Are there specific files within here that we should be including that are designed to be used on the web?

**Comment by MattIPv4** [comment]
No progress, closing.
