### ISSUE TITLE
Add labels for beginners

### ISSUE THREAD

**Issue by roy9495** [cdnjs/packages#1499]
There are no labels such as good-first-issue,beginner-friendly or good-first-contribution. Could you add these labels so the beginners can also contribute?

**Comment by raheemalzeeshan** [comment]
I am new to open source
Should I add "good-first-issue", "beginner-friendly", and "good-first-contribution" to this repo issue

**Comment by MattIPv4** [comment]
👋 Most of the open issues here are long-standing bugs in the cdnjs architecture, and I don't think they would be appropriate for new folks to be working on (unless you're rather brave and wish to spend a lot of time figuring out how cdnjs operates on your own), hence we aren't using those labels.
