### ISSUE TITLE
Add: babel-plugin-transform-async-to-promises

### ISSUE THREAD

**Issue by vitorklock** [cdnjs/packages#1500]
### Library name

babel-plugin-transform-async-to-promises

### Library license

https://github.com/rpetrich/babel-plugin-transform-async-to-promises/blob/master/LICENSE

### Library source

https://github.com/rpetrich/babel-plugin-transform-async-to-promises

### Files to include

- async-to-promises.js
- helpers-string.js
- helpers.js

**Comment by MattIPv4** [comment]
👋 `async-to-promises.js` makes use of Node.js `require` calls, which don't work in a web browser. As there web-compatible distributable files available for this project that we should be loading instead?

**Comment by MattIPv4** [comment]
No progress, closing.
