### ISSUE TITLE
Add: mozilla's readability

### ISSUE THREAD

**Issue by satreja1** [cdnjs/packages#1507]
### Library name

readability

### Library license

https://www.npmjs.com/package/@mozilla/readability?activeTab=code
http://www.apache.org/licenses/LICENSE-2.0

### Library source

https://www.npmjs.com/package/@mozilla/readability?activeTab=readme

### Files to include

- Readability.js

**Comment by MattIPv4** [comment]
👋 `readability.js` makes use of Node.js `require` calls, which don't work in a web browser. As there web-compatible distributable files available for this project that we should be loading instead?

**Comment by satreja1** [comment]
I couldn't find a web-compatible distributable version of this "readability" library but found a different library provided by Mozilla. I updated the description above to provide its link. 

Let me know if that works?
