### ISSUE TITLE
Add: @nutui/nutui

### ISSUE THREAD

**Issue by fly321** [cdnjs/packages#1510]
### Library name

@nutui/nutui

### Library license

https://github.com/jdf2e/nutui/blob/v4/LICENSE

### Library source

https://www.npmjs.com/package/@nutui/nutui

### Files to include

* \*

**Comment by MattIPv4** [comment]
👋 We cannot just add all the files from the library. Please could you specify what files are actually needed to be distributed via the CDN?

Is it just the `dist/nutui.umd.js` and `dist/style.css` files that are needed?

**Comment by fly321** [comment]
yes
dist/style.css
dist/nutui.umd.js
@nutui/icons-vue/dist/style_icon.css

**Comment by MattIPv4** [comment]
If you wish for us to have icons, please open a new issue for that package.
