### ISSUE TITLE
Add: webfont-lxgw-wenkai-screen

### ISSUE THREAD

**Issue by Jonathan523** [cdnjs/packages#1533]
### Library name

webfont-lxgw-wenkai-screen

### Library license

https://github.com/Jonathan523/lxgw-wenkai-webfont/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/webfont-lxgw-wenkai-screen

### Files to include

- CHANGELOG.md
- files
- *.css
- OFL.txt
- VERSION

**Comment by MattIPv4** [comment]
See https://github.com/cdnjs/packages/pull/1536#issuecomment-1529842697
