### ISSUE TITLE
Update: antd

### ISSUE THREAD

**Issue by jochenshi** [cdnjs/packages#1545]
### Library name

antd

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/a/antd.json

### Library source

https://www.npmjs.com/package/antd

### Files to include

- antd.js
- antd.min.js
- antd-with-locales.min.js
- antd-with-locales.js

**Comment by MattIPv4** [comment]
We have the latest version of antd available: https://cdnjs.com/libraries/antd/5.5.1
