### ISSUE TITLE
Add: Leaflet.StyledLayerControl

### ISSUE THREAD

**Issue by chrcorn** [cdnjs/packages#1547]
### Library name

Leaflet.StyledLayerControl

### Library license

https://github.com/davicustodio/Leaflet.StyledLayerControl/blob/master/LICENSE

### Library source

https://github.com/davicustodio/Leaflet.StyledLayerControl

### Files to include

- [styledLayerControl.js](https://github.com/davicustodio/Leaflet.StyledLayerControl/blob/master/src/styledLayerControl.js)
- [styledLayerControl.css](https://github.com/davicustodio/Leaflet.StyledLayerControl/blob/master/css/styledLayerControl.css)

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING.md](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md) document.
