### ISSUE TITLE
Add: psd.js

### ISSUE THREAD

**Issue by zheeeng** [cdnjs/packages#1548]
### Library name

psd.js

### Library license

https://github.com/meltingice/psd.js/blob/master/LICENSE.txt

### Library source

https://www.npmjs.com/package/psd.js

### Files to include

https://www.unpkg.com/psd.js@3.6.6/dist/index.js
https://www.unpkg.com/psd.js@3.6.6/dist/index.mjs

**Comment by SD007CSE** [comment]
Already added I think because: https://github.com/cdnjs/packages/blob/master/packages/p/psd.js.json

**Comment by zheeeng** [comment]
> Already added I think because: https://github.com/cdnjs/packages/blob/master/packages/p/psd.js.json

This published package is `pdf`, I'm requesting for `pdf.js`, they are two different packages with the same source code. The former is shipped with `AMD`, and the latter contains `ES Module` format which can be used in `module type script` and `vite bundler`.

**Comment by MattIPv4** [comment]
👋 I am not able to action this request -- the `psd.js` library config we have is already correctly pulling in the files distributed for that library. The files you have linked to from unpkg appear to be from an unknown source and do not appear to be published by the library itself.

If you wish for new files to be included in this library, please open an issue with the library maintainer. cdnjs will automatically pull in any new files included in new versions of the library.
