### ISSUE TITLE
Add: @nestechnology/turas-design-system

### ISSUE THREAD

**Issue by danielgreen** [cdnjs/packages#1563]
### Library name

@nestechnology/turas-design-system

### Library license

https://opensource.org/license/mit/

### Library source

https://www.npmjs.com/package/@nestechnology/turas-design-system

### Files to include

LICENSE.md
README.md
package.json
dist/css/turas-design-system.css
dist/css/turas-design-system.min.css
dist/js/turas-design-system.js
dist/js/turas-design-system.min.js
dist/img/android-chrome-96x96.png
dist/img/apple-touch-icon.png
dist/img/favicon-16x16.png
dist/img/favicon-32x32.png
dist/img/favicon.ico
dist/img/mstile-150x150.png

Please can the library be added with auto-update

**Comment by MattIPv4** [comment]
> dist/img/android-chrome-96x96.png
> dist/img/apple-touch-icon.png
> dist/img/favicon-16x16.png
> dist/img/favicon-32x32.png
> dist/img/favicon.ico
> dist/img/mstile-150x150.png

Why are these images needed? They are named like favicons for a website, yet this is a design library meant to be consumed by third-parties as I understand it?

I would also not that cdnjs does not support `ico` files.

**Comment by danielgreen** [comment]
It's a design library for a suite of related web apps that should share common styling, including favicons.

If the ico file cannot be hosted then can it be skipped please?

Please also include the following additional files:
dist/js/turas-design-system.init.js
dist/js/turas-design-system.init.min.js

Once the package is hosted on cdnjs, if other files are added to npmjs are they automatically picked up?

Thank you

**Comment by MattIPv4** [comment]
🤔 Is there an open-source repository for this? The NPM package seems to contain no reference to a source repository. We require a git repository to attribute the package to.

**Comment by MattIPv4** [comment]
> Once the package is hosted on cdnjs, if other files are added to npmjs are they automatically picked up?

Yes, you can see the config I'm adding in the PR above. I've used globs to look for all css/js files.
