### ISSUE TITLE
Add: @azure/storage-blob

### ISSUE THREAD

**Issue by locki13freja** [cdnjs/packages#1565]
### Library name

@azure/storage-blob

### Library license

https://github.com/Azure/azure-sdk-for-js/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/@azure/storage-blob

### Files to include

LICENSE.md
README.md
/documentation
/sdk

**Comment by MattIPv4** [comment]
The files you noted here for inclusion did not exist in the distributed package, nor did they make sense. I have included `dist/index.js` in the PR to add this library.

**Comment by locki13freja** [comment]
Thanks
