### ISSUE TITLE
Add: docsify-glossary

### ISSUE THREAD

**Issue by dhruvbalhara** [cdnjs/packages#1575]
### Library name

docsify-glossary

### Library license

https://github.com/stijn-dejongh/docsify-glossary/blob/main/LICENSE

### Library source

https://github.com/stijn-dejongh/docsify-glossary/releases/tag/v1.0.1

### Files to include

- docsify-glossary.min.js
- docsify-glossary.js

**Comment by MattIPv4** [comment]
https://github.com/cdnjs/packages/pull/1578#pullrequestreview-1511340932
