### ISSUE TITLE
Update: DevExtreme 23.1.3 (all *.js files are missing)

### ISSUE THREAD

**Issue by CyberGuerro** [cdnjs/packages#1579]
### Library name

DevExtreme-23.1.3

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/d/devextreme.json

### Library source

https://www.npmjs.com/package/devextreme

### Files to include

all javascripts files in **/js** folder. (to see which files consider to take a look into 22.2.6 package)

**Comment by MattIPv4** [comment]
> all javascripts files in /js folder.

There is no JS folder... do you mean the top-level cjs folder, rather than within dist?

**Comment by CyberGuerro** [comment]
I suspect that the origin package has missing files.... or the **dist/js/*.js** files had to be generated compiling the sources....
Unfortunately I don't know

**Comment by MattIPv4** [comment]
Ah okay, if either of those are true then this isn't a problem cdnjs can solve. We are only capable of hosting files that are present in the package itself, we cannot do any builds at runtime.

**Comment by CyberGuerro** [comment]
[Requested new package ](https://github.com/cdnjs/packages/issues/1582) for redistributable files as indicated on the official site.
No more needed dist files in this package
