### ISSUE TITLE
Add: devextreme-dist

### ISSUE THREAD

**Issue by CyberGuerro** [cdnjs/packages#1582]
### Library name

devextreme-dist

### Library license

https://github.com/DevExpress/DevExtreme/blob/23_2/LICENSE.md

### Library source

https://www.npmjs.com/package/devextreme-dist

### Files to include

All files

**Comment by MattIPv4** [comment]
👀 Would it make more sense to update devextreme on cdnjs to pull from devextreme-dist, rather than having devextreme with missing files, alongside a new devextreme-dist?

**Comment by CyberGuerro** [comment]
> eyes Would it make more sense to update devextreme on cdnjs to pull from devextreme-dist, rather than having devextreme with missing files, alongside a new devextreme-dist?

I think that if npm has created a new package with only dist files there is a motivated reason.
(But this is only my opinion)

If you want to change the DevExtreme cdnjs's package do it.
I'll wait any solution you will decide.

**Comment by MattIPv4** [comment]
> Sincerely I would prefer remove old devextreme package in favour of new devextreme-dist package..... I think it would be cleaner.

cdnjs does not support removing packages. Once they are published on the CDN, they must remain published forever.

I'll add devextreme-dist as a new package to avoid confusion

**Comment by CyberGuerro** [comment]
Can someone merge the pull-request? I'd like to get new package in my .net project.

thx to @MattIPv4  for new package who will merge it

**Comment by CyberGuerro** [comment]
No one?  I need it to develop my project.
Thx

**Comment by CyberGuerro** [comment]
Just one question @MattIPv4 :
Now package is in repository, but there are only 23.1.2 beta and alpha, instead of 23.1.3 which is a npm stable version.
Why 23.1.3 isn't in repository?

Thank you
