### ISSUE TITLE
Add: replicate

### ISSUE THREAD

**Issue by rajeevmsn** [cdnjs/packages#1585]
### Library name

replicate

### Library license

https://github.com/replicate/replicate-javascript/blob/main/LICENSE

### Library source

https://github.com/replicate/replicate-javascript

### Files to include

- index.js
- index.d.ts
- index.test.ts
- jest.config.js

**Comment by MattIPv4** [comment]
This library (in the `index.js` file) makes use of Node.js `require` calls, which will not work in a web context. Is there a different, bundled file that we should be pulling in?

**Comment by MattIPv4** [comment]
No progress, closing.
