### ISSUE TITLE
Add: Pretendard GOV Font Upload Request

### ISSUE THREAD

**Issue by kms0219kms** [cdnjs/packages#1590]
### Library name

pretendard-gov

### Library license

https://github.com/orioncactus/pretendard/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/pretendard-gov

### Files to include

dist/web/* (ext: css, woff, woff2)

**Comment by kms0219kms** [comment]
@MattIPv4, I can access [this file (css file for normal font)](https://cdnjs.cloudflare.com/ajax/libs/pretendard-gov/1.3.8/static/pretendard-gov.css) but I cannot access [css file for variable font](https://cdnjs.cloudflare.com/ajax/libs/pretendard-gov/1.3.8/variable/pretendardvariable-gov-dynamic-subset.css).

Are there synced successfully? Can you check it for me?

**Comment by MattIPv4** [comment]
I am not quite sure what is happening here -- the logs would suggest it was never published to the CDN properly: https://github.com/cdnjs/logs/tree/prod/packages/p/pretendard-gov/1.3.8

I have flagged this internally for investigation.

**Comment by kms0219kms** [comment]
> I am not quite sure what is happening here -- the logs would suggest it was never published to the CDN properly: https://github.com/cdnjs/logs/tree/prod/packages/p/pretendard-gov/1.3.8
> 
> I have flagged this internally for investigation.

Yes, please. Any updates?
