### ISSUE TITLE
Add: lodash-match-pattern

### ISSUE THREAD

**Issue by anna-yo** [cdnjs/packages#1599]
### Library name

lodash-match-pattern

### Library license

https://github.com/mjhm/lodash-match-pattern/blob/master/LICENSE

### Library source

https://github.com/mjhm/lodash-match-pattern

### Files to include

My apologies but I don't have the knowledge what is has to be included.
I want to use it in Postman (https://blog.postman.com/adding-external-libraries-in-postman/) similar to https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.11.0/dayjs.min.js
I found https://cdn.jsdelivr.net/npm/lodash-match-pattern@2.3.1/index.min.js but this is not working as the used dependencies as "chalk" are not available.

**Comment by MattIPv4** [comment]
👋 This library makes use of Node.js `require` calls, which will not work in a browser environment. You'll need to ask the author of the library to include a bundled version it the NPM package that is compatible with browsers before we can add it to cdnjs.
