### ISSUE TITLE
Add: p5play

### ISSUE THREAD

**Issue by quinton-ashley** [cdnjs/packages#1602]
### Library name

p5play

### Library license

https://github.com/quinton-ashley/p5play/blob/main/LICENSE.md

### Library source

https://www.npmjs.com/package/p5play

### Files to include

p5play.js
p5play.min.js
planck.min.js

**Comment by quinton-ashley** [comment]
I get an error saying it's not found!
https://cdnjs.com/libraries?q=p5play

**Comment by MattIPv4** [comment]
👍 Have a bit of patience, once the config is merged here, there is still a bunch of automation that has to detect it and publish versions.

You can see what the automation is doing over in https://github.com/cdnjs/logs/commits/prod

**Comment by quinton-ashley** [comment]
Ah okay, it just said you closed the issue 3 hours ago though so I figured there must've been a problem and it didn't work.
