### ISSUE TITLE
Add: hexo-theme-redefine

### ISSUE THREAD

**Issue by EvanNotFound** [cdnjs/packages#1606]
### Library name

hexo-theme-redefine

### Library license

https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/LICENSE

### Library source

https://github.com/EvanNotFound/hexo-theme-redefine

### Files to include

- source/*

**Comment by MattIPv4** [comment]
👋 I'm looking at the content of this package and am a bit confused -- you're asking for all of `source` to be added, but this contains a lot of files that cdnjs does not support.

For example, your `source/css` directly appears to contain `.styl` files, which are not in the [cdnjs extension whitelist](https://api.cdnjs.com/whitelist).

Please could you clarify exactly which files and extensions you are wanting to be added to cdnjs here?

**Comment by EvanNotFound** [comment]
Hi!

Sorry for the confusion. I will list the files to contain below:

- source/js/*
- source/assets/*
- source/webfonts/*
- source/fonts/*
- source/fontawesome/*

These are all the files needed.

Thank you so much!

**Comment by MattIPv4** [comment]
Is there a need to include `webfonts` and `fontawesome`? They appear to just be copies on FontAwesome, which is already available on cdnjs... it seems like a waste of our resource to host duplicates of that.

**Comment by EvanNotFound** [comment]
Hmm.

On the other hand, some of the icons of my theme reply on this specific version of font awesome. Changing all the icons to adapt to other versions will be a lot more complicated. I would be glad if you could include it!

**Comment by EvanNotFound** [comment]
Thanks! Have a great day!
