### ISSUE TITLE
Add: puppeteer@17.1.3

### ISSUE THREAD

**Issue by vkouk** [cdnjs/packages#1617]
### Library name

puppeteer

### Library license

https://github.com/puppeteer/puppeteer/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/puppeteer

### Files to include

.

**Comment by alejorrojas** [comment]
Is this already added?

**Comment by MattIPv4** [comment]
Puppeteer is a Node.js library, it is not going to work on the web, so I'm not sure it'd make sense for cdnjs to host it.
