### ISSUE TITLE
Handsontable license changed from MIT to custom or free for non commercial usage 

### ISSUE THREAD

**Issue by josepsanzcamp** [cdnjs/packages#1620]
Hi team.

I have see that the handsontable has been updated the license from MIT to custom or free for non commercial usage.

Here you can see the first commit where they applied this change:

- https://github.com/handsontable/handsontable/releases/tag/7.0.0

I don't know if you have some mechanism to inform the users in your website that the MIT license only apply until the version 6.2.2, and therefore the version 7.0.0 uses another license, a lot of more restrictive that the MIT.

Thanks in advance by your great work.

Josep.

**Comment by MattIPv4** [comment]
We don't have a mechanism to show the license for each version, but we (anyone is welcome to open a PR), can update the license in the library metadata to be accurate to the latest version :)
