### ISSUE TITLE
Update: Datatables

### ISSUE THREAD

**Issue by cpistohl** [cdnjs/packages#1621]
### Library name

datatables

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/d/datatables.json

### Library source

https://www.npmjs.com/package/datatables.net

### Files to include

all available js and css files

**Comment by cpistohl** [comment]
https://github.com/DataTables/DataTables is a legacy repository
https://github.com/DataTables/DataTablesSrc is the new repo

**Comment by MattIPv4** [comment]
👀 Does https://cdnjs.com/libraries/datatables.net not have what you need? That should be pulling new versions from NPM

**Comment by MattIPv4** [comment]
Closing as unactionable, we already pull the latest versions datatables from NPM -- the linked repository contained source files that could not be distributed on cdnjs.
