### ISSUE TITLE
cdnjs Master "libs" Not Populating

### ISSUE THREAD

**Issue by gunjandatta** [cdnjs/packages#173]
The PR: https://github.com/cdnjs/packages/pull/115/files is still not showing an file in the master branch: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/gd-sprest/

It should have published by now correct?

**Comment by MattIPv4** [comment]
cc @xtuc

**Comment by xtuc** [comment]
I fixed that in the bot, it should be pushing the new version of your packages anytime

**Comment by MattIPv4** [comment]
Now available on cdnjs: https://cdnjs.com/libraries/gd-sprest :)

**Comment by xtuc** [comment]
https://cdnjs.com/libraries/gd-sprest
