### ISSUE TITLE
Why is xterm.js not updating?

### ISSUE THREAD

**Issue by mruoss** [cdnjs/packages#1734]
#1691 has been merged a while ago. Still, I can't see the library being updated on cdnjs.org or https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/xterm.

**Comment by MattIPv4** [comment]
https://github.com/cdnjs/logs/tree/prod/packages/x/xterm it looks like there have been no new versions of the library released since the updated config was merged on Dec 6, hence no updated on cdnjs.com

**Comment by mruoss** [comment]
Could it be because they renamed `xterm` to `@xterm/xterm` and published versions they had published earlier in the other repo with the same version number?

**Comment by MattIPv4** [comment]
Yes, if they're publishing versions that've already been published before, we will not detect/re-process them. Once a net-new version is released that we haven't seen before, we'll pick it up.

**Comment by mruoss** [comment]
Makes sense. Thanks for the answer.
