### ISSUE TITLE
uuid not showing up on cdnjs.com

### ISSUE THREAD

**Issue by ctavan** [cdnjs/packages#179]
In https://github.com/cdnjs/packages/pull/102 the uuid library was added and it is in master: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/uuid

However it does not show up on https://cdnjs.com/libraries/uuid

Is there any additional action that needs to be taken for it to show up?

**Comment by MattIPv4** [comment]
This will be due to how often the website/API update (twice daily I believe). It is now available on cdnjs: https://cdnjs.com/libraries/uuid

**Comment by xtuc** [comment]
Yes, it's twice daily https://github.com/cdnjs/bot-ansible/blob/master/templates/update-website.timer#L5-L7

**Comment by ctavan** [comment]
Oh, maybe my browser cache tricked me… I had to hard-refresh to see it appear on https://cdnjs.com/libraries/uuid

Thanks!
