### ISSUE TITLE
Update: flowbite

### ISSUE THREAD

**Issue by zoltanszogyenyi** [cdnjs/packages#1835]
### Library name

flowbite

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/f/flowbite.json

### Library source

https://www.npmjs.com/package/flowbite

### Files to include

- flowbite.js
- flowbite.css
- flowbite.js.map
- flowbite.min.css
- flowbite.min.js
- flowbite.min.js.map
- flowbite.phoenix.js
- flowbite.phoenix.js.map
- flowbite.phoenix.min.js
- flowbite.phoenix.min.js.map
- flowbite.turbo.js
- flowbite.turbo.js.map
- flowbite.turbo.min.js
- flowbite.turbo.min.js.map

**Comment by MattIPv4** [comment]
@xtuc something seems rather wrong here... looking at https://github.com/cdnjs/logs/commits/prod/ nothing seems to be getting actually processed/published.

Looking at https://github.com/cdnjs/logs/tree/prod/packages/f/flowbite/2.4.0 specifically, it looks like it was partially published, which might explain why it does on the site but with no files? Interestingly https://github.com/cdnjs/logs/blob/prod/packages/f/flowbite/2.4.0/processing.log contains a single line reporting the disk is full?

**Comment by zoltanszogyenyi** [comment]
Hey @MattIPv4 ,

Appreciate the response. I'm not at my computer at the moment but all other CDN's picked up on the new versions without issues. On NPM all files are available - am I missing something? Did a npm release just like any other, not sure what to do ☹️

Cheers,
Zoltan

**Comment by MattIPv4** [comment]
This is not an issue on your end, it is an issue on our end as I explained in my previous reply.

**Comment by xtuc** [comment]
Fixed https://github.com/cdnjs/logs/commit/118a77882332e1857374878558cb54cc4e36e75d
