### ISSUE TITLE
Invalid git repositories

### ISSUE THREAD

**Issue by xtuc** [cdnjs/packages#185]
At the moment the new bot noticed that the following packages were using an invalid git repository for their updates:

6/6px.json: invalid git repo 
c/custommarkup.json: invalid git repo 
d/darktooltip.json: invalid git repo 
e/ember.js.json: invalid git repo 
g/gist-embed.json: invalid git repo 
m/mogl.json: invalid git repo 
p/probtn.json: invalid git repo 
r/rainyday.js.json: invalid git repo 
s/scrollmonitor.json: invalid git repo 
s/snoocore.json: invalid git repo 
t/Tipue-Search.json: invalid git repo 

List is incomplete.

**Comment by MattIPv4** [comment]
6/6px.json: invalid git repo -- Abandoned project
c/custommarkup.json: invalid git repo -- Abandoned project

d/darktooltip.json: invalid git repo -- Unsure why this is invalid, seems fine to me. https://github.com/cdnjs/packages/blob/master/packages/d/darktooltip.json & https://github.com/rubentd/darktooltip/tree/v0.4.0/dist

e/ember.js.json: invalid git repo -- https://github.com/components/ember is no longer being updated, maybe `dist/ember.debug.js` from `ember-source`?

g/gist-embed.json: invalid git repo
m/mogl.json: invalid git repo
p/probtn.json: invalid git repo
r/rainyday.js.json: invalid git repo
s/scrollmonitor.json: invalid git repo
s/snoocore.json: invalid git repo
t/Tipue-Search.json: invalid git repo

**Comment by MattIPv4** [comment]
Closing, the only addressable invalid repo has been fixed.
