### ISSUE TITLE
Add Snowplow sp.js

### ISSUE THREAD

**Issue by jaideeprana** [cdnjs/packages#254]
Could it be possible for you guys to include snowplow sp.js in one of your lists

**Comment by paulboocock** [comment]
Hi @MattIPv4 
Looking for a little advice. This is a slightly odd approach, I must admit, but we've been looking at options to offer third-party CDN options sooner and for our historical releases too. So what we've done is to start publishing our sp.js asset to a GitHub repo as a tagged release: https://github.com/snowplow/sp-js-assets/blob/2.16.0/sp.js

We've done this to help us get onto third-party CDNs a little faster than waiting for v3 (and allows users of v2 to switch off our CDN without needing to fully switch to v3). I'm happy to follow your guide for auto updating github repos [here](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#git-based-auto-update-example), assuming you're ok to waive the 200 stars requirement on this repo (given the [main repo](https://github.com/snowplow/snowplow-javascript-tracker) has ~400 hopefully thats ok?).

My question is when v3 launches, we'll start publishing to npm later this year but I'd like to keep the github repo for v2 around (and probably archive the repo but keep the releases on CDNs) and then move v3 to auto-updating npm releases. What would the steps be for this? Is this a reasonable approach?

Once confirmed, I'll sort out a PR for you on the GitHub side.

**Comment by MattIPv4** [comment]
> assuming you're ok to waive the 200 stars requirement on this repo 

Yup. Git auto-update sounds good 👍 

> What would the steps be for this? Is this a reasonable approach?

Assuming you'd be publishing no new v2 releases, you'd just create a PR to change the auto-update config here to target NPM (assuming it has pre-bundled assets) and we'd start pulling those in.

**Comment by paulboocock** [comment]
Perfect. I'll get this submitted shortly!
