### ISSUE TITLE
Update DataTables

### ISSUE THREAD

**Issue by mrlife** [cdnjs/packages#256]
Latest version of DataTables (1.10.20) appears to need manual attention to start loading automatically again.

See: https://github.com/cdnjs/cdnjs/issues/13524#issuecomment-577415058

**Comment by DataTables** [comment]
Sorry for the delay - I lost track of this. Yes - that's it done!

**Comment by MattIPv4** [comment]
`1.10.21` is now on cdnjs: https://cdnjs.com/libraries/datatables/1.10.21 -- Thanks!
