### ISSUE TITLE
Update vuex

### ISSUE THREAD

**Issue by benleilei** [cdnjs/packages#257]
https://github.com/vuejs/vuex is on 3.4.0, CDNJS only has 3.2.0 and it causes errors with their latest documentation. CDNJS missing 3.3.0 and 3.4.0 two version.

**Comment by xtuc** [comment]
The last version that cdnjs has is `4.0.0-beta.2`, the bot is only pushing new versions. Technically `3.4.0` is behind.
We would need to change that logic to include previous versions.

**Comment by xtuc** [comment]
Since we removed the only increasing semver restriction:
```
commit 7e687020b4256d20d563388de83d2d17aae10c71
Author: robocdnjs <cdnjs-github@cloudflare.com>
Date:   Tue Jun 30 13:13:44 2020 +0000

    Add vuex v3.5.1

commit 8fb6d810b6df852a7f0a8528cd56998e1716e3a4
Author: robocdnjs <cdnjs-github@cloudflare.com>
Date:   Tue Jun 30 13:12:58 2020 +0000

    Add vue v3.0.0-beta.16
```
