### ISSUE TITLE
Add CLDR JSON files

### ISSUE THREAD

**Issue by AnReZa** [cdnjs/packages#258]
_Globalize.js_ is currently hosted on CDNJS. It mandatorily requires various static JSON files from the Unicode Common Locale Data Repository (CLDR), as described [here](https://github.com/globalizejs/globalize/blob/master/doc/cldr.md). Without those files, Globalize won't function. Unfortunately, those files can't be found on CDNJS yet, hence you would need to host them locally, which would speak against the idea of a centralized hosting service.

Would you please add those dependencies to the CDNJS?

This is a follow-up to cdnjs/cdnjs#10160 and cdnjs/cdnjs#13450.

**Comment by MattIPv4** [comment]
No progress, closing.

**Comment by MattIPv4** [comment]
Turns out https://github.com/unicode-org/cldr-json has now been created and appears to contain all the JSON files in single tagged repo, so this should be possible now!
