### ISSUE TITLE
Add: ManUp.js

### ISSUE THREAD

**Issue by aravindvnair99** [cdnjs/packages#272]
**Library name:** ManUp.js

**Library license (include link):** [Apache-2.0](https://github.com/boyofgreen/ManUp.js/blob/master/LICENSE)

**Library source (NPM package or Git repo):** https://github.com/boyofgreen/ManUp.js

**Comment by MattIPv4** [comment]
Per https://github.com/cdnjs/packages/pull/273#issuecomment-653771559, auto-update is not available for this library, so we cannot add it. Closing.
