### ISSUE TITLE
Update: fetch

### ISSUE THREAD

**Issue by e965** [cdnjs/packages#293]
**Library name:** fetch (whatwg-fetch)

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/f/fetch.json

**Library source (NPM package or Git repo):** https://github.com/github/fetch https://www.npmjs.com/package/whatwg-fetch

The current version is 3.1.0, but only 3.0.0 is available on the CDN.

**Comment by MattIPv4** [comment]
@tc80 wondering if you have time to take a look at this? The [3.1.0 version was released Jun 30th at 10:19 UTC]](https://github.com/github/fetch/releases/tag/v3.1.0), but looking at the logs from the 23:00 to 23:59 run on the 30th, the bot was still only seeing 3.0.0 as the latest tag?

```
{"insertId":"SNIP","labels":{"compute.googleapis.com/resource_name":"cdnjs-bot-6"},"logName":"projects/cdnjs-SNIP/logs/syslog","receiveTimestamp":"2020-06-30T23:30:37.482093003Z","resource":{"labels":{"instance_id":"SNIP","project_id":"cdnjs-SNIP","zone":"europe-west2-c"},"type":"gce_instance"},"textPayload":"Jun 30 23:26:41 cdnjs-bot-6 autoupdate[30755]: 2020/06/30 23:26:41 f/fetch.json: found tags in git: [v0.1.0 v0.10.0 v0.10.1 v0.11.0 v0.11.1 v0.2.0 v0.2.1 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.5.0 v0.6.0 v0.6.1 v0.7.0 v0.8.0 v0.8.1 v0.8.2 v0.9.0 v1.0.0 v1.1.0 v1.1.1 v2.0.0 v2.0.1 v2.0.2 v2.0.3 v2.0.4 v3.0.0]","timestamp":"2020-06-30T23:26:41Z"}
```

There's a chance that once we start the bot back up once NPM resolves their issue, it might just see the new tag and pull it in, but it seems odd it was missing during this run?

**Comment by tc80** [comment]
Weird! Looking into it now

**Comment by tc80** [comment]
After running `show-files`, the version `3.1.0` is recognized as the latest. 

When we run the bot again after fixing the NPM issue, I will check the logs to see if it finds `3.1.0`. If not, then there is likely a bug due to the recent switch from sorting versions by semver to time stamp.

Either way, it should be fixed soon! 👍

**Comment by tc80** [comment]
```2020-07-03 00:15:59.000 EDT
Jul 3 04:15:59 cdnjs-bot-6 autoupdate[598]: 2020/07/03 04:15:59 f/fetch.json: found tags in git: [v0.1.0 v0.10.0 v0.10.1 v0.11.0 v0.11.1 v0.2.0 v0.2.1 v0.3.0 v0.3.1 v0.3.2 v0.4.0 v0.5.0 v0.6.0 v0.6.1 v0.7.0 v0.8.0 v0.8.1 v0.8.2 v0.9.0 v1.0.0 v1.1.0 v1.1.1 v2.0.0 v2.0.1 v2.0.2 v2.0.3 v2.0.4 v3.0.0]```

Bot is running, and looks like we are failing to fetch all the tags! Will test and fix this tomorrow, thanks for noticing the issue @e965.

@xtuc

**Comment by xtuc** [comment]
I'm unsure why but `git tag` wouldn't show the new tag even if I manually update the git cache. I cleared the cache and the bot picked up the new version 5099b20f2ac1c736c212ae8df7a33c1f87b42785
