### ISSUE TITLE
Add: tui.code-snippet

### ISSUE THREAD

**Issue by si458** [cdnjs/packages#297]
**Library name:** tui.code-snippet

**Library license (include link):** [MIT License](https://github.com/nhn/tui.code-snippet/blob/master/LICENSE)

**Library source (NPM package or Git repo):** https://github.com/nhn/tui.code-snippet

TO BE USED WITH [tui.calendar](https://github.com/nhn/tui.calendar) which is already on [cdnjs.com](https://cdnjs.com/libraries/tui-calendar)

**Comment by si458** [comment]
Brilliant thanks
How long before it’s on cdnjs.com ?

**Comment by MattIPv4** [comment]
Sorry for the delay, looks like it is now available on the website at https://cdnjs.com/libraries/tui-code-snippet and the API at https://api.cdnjs.com/libraries/tui-code-snippet

**Comment by si458** [comment]
@MattIPv4 brilliant thanks! 👍 
have requested a few others of there products as they are brilliant but there CDN is poo...
