### ISSUE TITLE
Consider GitHub stars for NPM auto-update

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/packages#299]
Currently, the CI only considers the NPM downloads for checking popularity when a package is configured with NPM auto-update. If a repository is also defined in the JSON file, we should also consider the stars on this for popularity.

If the packages reaches either of the popularity checks in this situation, we should be able to accept the package.

An example of this was seen in #294 where the NPM package `normalize-opentype.css` didn't reach the 800 downloads per month, but the library still reaches our popularity requirement through the GitHub repo with > 200 stars, https://github.com/kennethormandy/normalize-opentype.css

**Comment by klausenbusk** [comment]
PR opened: https://github.com/cdnjs/tools/pull/94
