### ISSUE TITLE
Update: es6-promise

### ISSUE THREAD

**Issue by klausenbusk** [cdnjs/packages#300]
The `dist` directory was removed from the es6-promise git repository some time ago (https://github.com/stefanpenner/es6-promise/pull/312).

The following versions is missing:
```
4.2.8
4.2.7
4.2.6
4.2.5
4.2.4
4.2.3
4.2.2
4.2.1
4.2.0
```
Relevant `autoupdate` "error":
```
2020/07/04 15:37:51 e/es6-promise.json: match **/* in /home/kristian/Hentet/cdnjs/git-cache/es6-promise/dist but doesn't exists
2020/07/04 15:37:51 e/es6-promise.json: no files matched
```

**Library name:** es6-promise

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/e/es6-promise.json

**Library source (NPM package or Git repo):** Git at the moment, but we should switch to NPM

**Files to include:** The current configuration seems to be fine

I will open a PR if I don't forget.

**Comment by klausenbusk** [comment]
> Relevant `autoupdate` "error":

We should probably make a list of "broken" packages and add a `skip` option, so we don't waste time on broken packages.

**Comment by MattIPv4** [comment]
Adding a way to force packages to be skipped sounds like something that is jsut going to increase complexity in maintaining cdnjs, I'd much rather all packages are always considered.

**Comment by klausenbusk** [comment]
> Adding a way to force packages to be skipped sounds like something that is just going to increase complexity in maintaining cdnjs, I'd much rather all packages are always considered.

I partly agree, but it is hard to make `autoupdate` fast if we need to clone (too) many repositories just to discover that something is broken. Lets wait and see :)

**Comment by MattIPv4** [comment]
If there are broken packages that are slowing the bot down, we should be fixing them or removing the auto-update config from them. Adding new logic just to skip isn't the right solution.
