### ISSUE TITLE
Update: rellax.js

### ISSUE THREAD

**Issue by alextaghavi** [cdnjs/packages#332]
**Library name:** Rellax.js

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/r/rellax.json

**Library source (NPM package or Git repo):** https://www.npmjs.com/package/rellax

**Files to include:** 

https://cdnjs.cloudflare.com/ajax/libs/rellax/1.11.0/rellax.min.js

should be: 1.12.1 --> https://github.com/dixonandmoe/rellax/blob/master/rellax.min.js

**Comment by klausenbusk** [comment]
Hmm, the https://github.com/cdnjs/packages/blob/master/packages/r/rellax.json file looks right and `checker` doesn't complain:
```
most recent version: 1.12.1

rellax.js
rellax.min.js

9 last version(s):
- 1.12.0: 2 file(s) matched :heavy_check_mark:
- 1.11.0: 2 file(s) matched :heavy_check_mark:
- 1.10.0: 2 file(s) matched :heavy_check_mark:
- 1.9.1: 2 file(s) matched :heavy_check_mark:
- 1.9.0: 2 file(s) matched :heavy_check_mark:
- 1.8.1: 2 file(s) matched :heavy_check_mark:
- 1.8.0: 2 file(s) matched :heavy_check_mark:
- 1.7.2: 2 file(s) matched :heavy_check_mark:
- 1.7.1: 2 file(s) matched :heavy_check_mark:
```

**Comment by MattIPv4** [comment]
https://cdnjs.com/libraries/rellax/1.12.1 is available, has been for 5 months: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/rellax/1.12.1

I wonder why the bot has updated the `version` in https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/rellax/package.json

**Comment by MattIPv4** [comment]
Bot has updated the version: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/rellax/package.json
