### ISSUE TITLE
angular-material version not found!

### ISSUE THREAD

**Issue by klausenbusk** [cdnjs/packages#337]
I think this is related to the heavily use of tags: https://github.com/angular/bower-material/commits/master, the bot has changed the [version](https://github.com/cdnjs/cdnjs/commit/d4e291e3aa82034c0ed7e351d0cc39ed9fe78878) in the `package.json` to `1.1.24-master-7157b3b`, but `1.1.24-master-7157b3b` hasn't been added (`1.1.24` exists though)

**Comment by MattIPv4** [comment]
@tc80 one for you to take a look at?

**Comment by klausenbusk** [comment]
Let's wait and see if this is fixed by: https://github.com/cdnjs/tools/pull/100

**Comment by MattIPv4** [comment]
Sweet (the new website also has logic to avoid this -- https://cdnjs.dev/libraries/angular-material)

**Comment by klausenbusk** [comment]
Fixed yeh.. https://github.com/cdnjs/cdnjs/commit/2900231ba55e735eab11f2180a1ee67291029f68
