### ISSUE TITLE
Add Ant Design Blazor

### ISSUE THREAD

**Issue by jiqing112** [cdnjs/packages#348]
**Library name:** Ant Design Blazor

**Library license (include link):** MIT
**Library source (NPM package or Git repo):** https://github.com/ant-design-blazor/ant-design-blazor

**Comment by MattIPv4** [comment]
@jiqing112 Which files do we need from that repository?

**Comment by ElderJames** [comment]
Hi, thank you for your help!
we need to host the files in the following directories:

- Blazor Webassembly Framework: https://github.com/ant-design-blazor/ant-design-blazor.github.io/tree/master/_framework
- Ant Design Blazor Files: https://github.com/ant-design-blazor/ant-design-blazor.github.io/tree/master/_content/AntDesign

**Comment by MattIPv4** [comment]
That repository isn't tagged with semver, so we cannot pull files from it

**Comment by ElderJames** [comment]
Ok, let me see what I can do.

**Comment by ElderJames** [comment]
Hi @MattIPv4 , can we use this repo?

https://github.com/ant-design-blazor/blazor-wasm-assets/tree/master/dist/0.1.0/wwwroot

**Comment by MattIPv4** [comment]
@ElderJames I'm guessing there that the directory would change for each version, which isn't something we can support -- the files need to be in a consistent directory.

**Comment by ElderJames** [comment]
Ok~

**Comment by ElderJames** [comment]
@MattIPv4  I have published a npm package for it. I think it's more convenient!

https://www.npmjs.com/package/ant-design-blazor

**Comment by MattIPv4** [comment]
There are a huge number of dll files and other unsupported file extensions (gz, br) in the package. Which files exactly are needed to be hosted on cdnjs?

**Comment by ElderJames** [comment]
Just dll,js,css,svg and json files are needed.The gz and br files are for server side compress.

**Comment by MattIPv4** [comment]
We cannot host dll files, only the extensions listed at https://api.cdnjs.com/whitelist?fields=extensions, so js, css, svg & json from what you listed.

**Comment by ElderJames** [comment]
Ok, I am so sorry.
