### ISSUE TITLE
404 Error: Algolia 

### ISSUE THREAD

**Issue by JamesVanWaza** [cdnjs/packages#354]
**Library name:** AlgoliaSearch

**Library JSON file link:** https://cdnjs.cloudflare.com/ajax/libs/algoliasearch/4.3.1/algoliasearch.min.js

Please note the following page is showing a 404 error. Thank you.

**Comment by MattIPv4** [comment]
@tc80 didn't we add logic to the bot so that `filename` would always be set to a valid file?

**Comment by tc80** [comment]
I made a PR for it but [closed it a few days ago](https://github.com/cdnjs/tools/pull/98).
I thought the website changed its logic to always pick a valid file. I think I'm going crazy @MattIPv4 😆 

Will check this out tomorrow

**Comment by JamesVanWaza** [comment]
@tc80 what's the status?

**Comment by tc80** [comment]
@JamesVanWaza the issue will be fixed when algoliasearch publishes a new version.

@MattIPv4 I can fix this now if I make a tool to go over all existing metadata and fix any invalid `filename` properties. Should I do this or do you think it's okay to just fix the issue when new versions are published? Either way the issue will get fixed eventually 👍

**Comment by MattIPv4** [comment]
Considering how many libraries likely fall into this bug, I think it's probably worth writing a quick script to update existing files 👍

**Comment by tc80** [comment]
Ok will do. @JamesVanWaza I will close this when fixed 👍

**Comment by tc80** [comment]
Okay @MattIPv4 since not all packages are in KV yet, it is difficult to query the assets for a particular version.

I will upload `algoliasearch` manually and this will fix the `filename` issue for this specific case. The other libraries will be fixed automatically when another version is released, or when we upload all the remaining packages to KV.

**Comment by tc80** [comment]
[All set](https://github.com/cdnjs/cdnjs/commit/474c4bb6221c4c9cb40fb474e4cf3ecdacaeabb4). Website will update in 10 hours or so, and should be all fixed for `algoliasearch` 😄 

```
Aug 02 19:47:04 cdnjs-bot-6 autoupdate[3580]: 2020/08/02 19:47:04 a/algoliasearch.json: Updated `algoliasearch/4.3.1` filename `algoliasearch.min.js` -> `algoliasearch.cjs.js`
```
