### ISSUE TITLE
Add: hexo-theme-next

### ISSUE THREAD

**Issue by stevenjoezhang** [cdnjs/packages#405]
**Library name:** hexo-theme-next

**Library license (include link):** [AGPL3](https://github.com/next-theme/hexo-theme-next/blob/master/LICENSE.md)

**Library source (NPM package or Git repo):** https://github.com/next-theme/hexo-theme-next
https://www.npmjs.com/hexo-theme-next

**Comment by MattIPv4** [comment]
Hi,

What files from this package are you looking to have added to cdnjs? All the JavaScript files in the package seem to be Node.js files, which won't work with a web CDN -- they need to be compiled through a build pipeline.

**Comment by stevenjoezhang** [comment]
Hello, the front-end scripts are placed in the `source/js` directory:
https://github.com/next-theme/hexo-theme-next/tree/master/source/js

This package is a bit special because it is a theme designed for the static website generator Hexo.

Thank you!
