### ISSUE TITLE
add on-change library

### ISSUE THREAD

**Issue by DanielIndie95** [cdnjs/packages#418]
**Library name:** on-change

**Library license (include link):** https://github.com/sindresorhus/on-change MIT-License

**Library source (NPM package or Git repo):** https://github.com/sindresorhus/on-change

**Comment by DanielIndie95** [comment]
@MattIPv4 hey, could you have a look ? :)

**Comment by MattIPv4** [comment]
It's on my list, will take a look this week most likely :)

**Comment by MattIPv4** [comment]
Unfortunately, it looks like the library doesn't provide a bundled version of itself, only a Node.js version. The Node.js version relies on `require` calls which won't in a browser, so we can't add this to cdnjs.
