### ISSUE TITLE
Add: ztext

### ISSUE THREAD

**Issue by pieter-biesemans** [cdnjs/packages#428]
**Library name:** ztext

**Library license (include link):** MIT (https://github.com/bennettfeely/bennett/blob/master/ztext/LICENSE)

**Library source (NPM package or Git repo):** https://github.com/bennettfeely/bennett/tree/master/ztext

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md) document.
