### ISSUE TITLE
CI fails on PRs from forks

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/packages#44]
See #43 for context.

GitHub Actions doesn't pass custom secrets to PRs from forks for secuirty reasons, which means that the CI doesn't have the robocdnjs token to comment & approve.

I think it might be better to use the GitHub Actions built-in token for commenting & approving, so that it works everywhere.

**Comment by xtuc** [comment]
I have some ideas to make it work but I don't think it's worth the effort. I will change that use the default token.

**Comment by xtuc** [comment]
https://github.com/cdnjs/packages/commit/a7adc4b69ddce490112e96d81d831b6af3bb9da2
