### ISSUE TITLE
[Update Request] echarts 4.9.0 and package configuration

### ISSUE THREAD

**Issue by plainheart** [cdnjs/packages#442]
Hi cdnjs team, I'm opening this issue to request an update of echarts of the new version 4.9.0.
In addition, echarts is now under incubation at Apache Software Foundation, please update the package configuration as well.

**Library name:** echarts

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/e/echarts.json

**Library source (NPM package or Git repo):** https://www.npmjs.com/package/echarts

**Files to include:** all files in dist

Thank you!

**Comment by MattIPv4** [comment]
@plainheart It looks like echarts released both 4.9.0 & 4.9.0-rc.1 from the same commit in git, so we picked up the initial 4.9.0-rc.1 version, which is available on cdnjs (https://cdnjs.com/libraries/echarts/4.9.0-rc.1) -- this is identical to 4.9.0.

I'll create a PR to update the license/homepage/repo.

**Comment by plainheart** [comment]
@MattIPv4 Thank you very much! I would like to suggest, in the next, we pick up the newest release version instead of the release candidate version(like x.x.x-rc.x) if there were two versions from the same commit.

**Comment by MattIPv4** [comment]
@tc80 should be able to confirm, but I imagine that the bot will simply be getting the first tag from that commit, so we'd always pick up the rc1 version if it was tagged on the same commit that the final version was then released on.

Two simple solutions to this: 1. y'all release versions on unique commits 2. we move the package to auto-updating from NPM

**Comment by plainheart** [comment]
Thanks! I prefer the second solution. Let's move the package to auto-updating from NPM.

**Comment by MattIPv4** [comment]
👍 Let's leave it on git auto-update then I'll just hope y'all don't release the same commit as two different versions.
