### ISSUE TITLE
Add: arkane-connect

### ISSUE THREAD

**Issue by davyvanroy** [cdnjs/packages#448]
**Library name:** 
arkane-connect

**Library license (include link):** 
[MIT](https://github.com/ArkaneNetwork/arkane-connect/blob/develop/LICENSE)

**Library source (NPM package or Git repo):** 

- https://www.npmjs.com/package/@arkane-network/arkane-connect
- https://github.com/ArkaneNetwork/arkane-connect

**Comment by MattIPv4** [comment]
The GitHub repository linked appears to 404. The linked NPM package does not include a pre-bundled version from what I can tell, the only files in there rely on `require`, which does not work in a browser.

**Comment by MattIPv4** [comment]
Ah, nvm, I see `connect.js` seems to be bundled
