### ISSUE TITLE
Add: kubernetes

### ISSUE THREAD

**Issue by sam-myers** [cdnjs/packages#451]
**Library name:** kubernetes

**Library license (include link):** [Apache 2.0](https://github.com/kubernetes-client/javascript/blob/master/LICENSE)

**Library source (NPM package or Git repo):** https://github.com/kubernetes-client/javascript

**Comment by MattIPv4** [comment]
👋  Neither the linked NPM package nor the GitHub repo include a pre-bundled version from what I can tell, the only files in there rely on require, which does not work in a browser. We need a versioned source that includes a pre-bundled version of the library before we can add it to cdnjs.

**Comment by MattIPv4** [comment]
No progress, closing.
