### ISSUE TITLE
There is no UPNG.encodeLL function in the latest version upng-js 2.1.0. Does it need to be updated?

### ISSUE THREAD

**Issue by pxp1230** [cdnjs/packages#458]
**Library name:** upng-js

**Library JSON file link:** https://github.com/photopea/UPNG.js/blob/master/package.json

**Library source (NPM package or Git repo):** https://github.com/photopea/UPNG.js

**Files to include:** UPNG.js

**Comment by MattIPv4** [comment]
We have the latest version available: https://cdnjs.com/libraries/upng-js/2.1.0
