### ISSUE TITLE
Add: Rough-Notation & Vanilla-Rough-Notation

### ISSUE THREAD

**Issue by Julianwan** [cdnjs/packages#462]
_Hello! This is my first time opening a request. I've tried to follow the contributing guidelines closely. Please help me understand if I made any errors when opening this ticket. Thank you!_

**Library name:** rough-notation
- _current version: 0.4.0_
- _12 historic versions_
- _last updated 4 months ago_

**Library license ([GitHub link](https://github.com/rough-stuff/rough-notation/blob/master/LICENSE)):** MIT

**Library source (Both are NPM links, and documented on GitHub):**

- **NPM:** [rough-notation](https://www.npmjs.com/package/rough-notation) _1,384 weekly downloads as of 10/20/2020_
- **NPM:** [vanilla-rough-notation](https://www.npmjs.com/package/vanilla-rough-notation) _much fewer downloads, but related_

**Description**:
Rough Notation is a popular annotator based on Rough.js that allows for adding interesting overlays and notation animations for individual elements on a page.

**Purpose of Request:** The current [Github Documentation](https://github.com/rough-stuff/rough-notation) for rough-notation provide simple steps for import, but the module import can be a pain for popular services like Webflow, Wix, and other client-preferred platforms where this sort of annotation effect seems very "premium" to the clients — but implementation is difficult without a vanilla JS version available.

**Demo Page:** [Official Site](https://roughnotation.com)

![Sample Image](https://roughnotation.com/images/social.png)

**Comment by MattIPv4** [comment]
We can add rough-notation, but not vanilla-rough-notation as it does not meet the popularity requirement

**Comment by Julianwan** [comment]
Thank you, that's still awesome. Um... do I close this ticket?

**Comment by MattIPv4** [comment]
Nope, it will automatically close once the library is added
