### ISSUE TITLE
support new Library BizCharts

### ISSUE THREAD

**Issue by heiniuhaha** [cdnjs/packages#465]
**Library name:** 
BizCharts

**Library license (include link):**  
BizCharts is available under the License MIT. 
https://github.com/alibaba/BizCharts/blob/master/README.md

**Library source (NPM package or Git repo):** 
https://github.com/alibaba/BizCharts
npm install bizcharts

**Comment by heiniuhaha** [comment]
When is it expected that bizCharts CDN will come into effect on CDNJS official website? Thank you very much

**Comment by MattIPv4** [comment]
Once this issue is closed by the PR being merged, should be within two hours.
