### ISSUE TITLE
It isn't clear how libraries get on CDNjs

### ISSUE THREAD

**Issue by trusktr** [cdnjs/packages#466]
Besides finding this repo, there's like no documentation anywhere.

Do we publish to NPM and CDNjs automatically mirrors it? Or we only request manually here?

EDIT: Oh wait, I may be thinking about jsdelivr. Is there any automatic mirroring of other sources in CDNjs like on jsdelivr?

**Comment by trusktr** [comment]
I'm trying to figure out how versions of `@tweenjs/tween.js` end up on on cdnjs (I'm maintaining that). For example: https://cdnjs.cloudflare.com/ajax/libs/tween.js/17.3.0/Tween.min.js

**Comment by MattIPv4** [comment]
As noted in https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#auto-update-overview, libraries are updated by an auto-update bot, based on git/npm releases. You can see the auto-update config for tween.js here: https://github.com/cdnjs/packages/blob/master/packages/t/tween.js.json

**Comment by MattIPv4** [comment]
No progress, closing.
