### ISSUE TITLE
[Request Update] twemoji

### ISSUE THREAD

**Issue by RikoDEV** [cdnjs/packages#475]
**Library name:** twemoji

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/t/twemoji.json

**Library source (NPM package or Git repo):** https://github.com/twitter/twemoji

**Files to include:** 13.0.1

**Comment by MattIPv4** [comment]
So it looks like the git repo no longer has the scripts in it, and the NPM package no longer has the assets in it.

Do you agree that it'd be fine to just host the assets from https://github.com/twitter/twemoji/tree/master/assets ?

**Comment by lovelxc** [comment]
> So it looks like the git repo no longer has the scripts in it, and the NPM package no longer has the assets in it.
> 
> Do you agree that it'd be fine to just host the assets from https://github.com/twitter/twemoji/tree/master/assets ?

Can u merge the js scripts on https://www.npmjs.com/package/twemoji (tag 14.0.2)

**Comment by MattIPv4** [comment]
No, we cannot combine multiple sources into a single package.

**Comment by lovelxc** [comment]
> No, we cannot combine multiple sources into a single package.

What about create a new package for https://www.npmjs.com/package/twemoji such as 'twemoji-js'?

**Comment by MattIPv4** [comment]
Sure, feel free to open a PR to add it.

**Comment by lovelxc** [comment]
> Sure, feel free to open a PR to add it.

I will try to do this.
