### ISSUE TITLE
Please update jqueryAjaxQueue with correct reference to map

### ISSUE THREAD

**Issue by aztechowski** [cdnjs/packages#491]
Including //cdnjs.cloudflare.com/ajax/libs/jquery-ajaxQueue/0.1.1/jquery.ajaxQueue.min.js causes an error in Chrome "DevTools failed to load SourceMap: Could not load content for https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxQueue/0.1.1/dist/jquery.ajaxQueue.min.map"

**Library name:** jquery-ajaxQueue

**Library JSON file link:** https://github.com/gnarf/jquery-ajaxQueue/blob/master/ajaxQueue.jquery.json

**Library source (NPM package or Git repo):** Git repo

**Files to include:** all dist files

**Comment by MattIPv4** [comment]
This is an issue with the source package, not cdnjs. The minified file references the map incorrectly in the `dist` subdirectory, when it is actually at the same level: https://github.com/gnarf/jquery-ajaxQueue/blob/master/dist/jquery.ajaxQueue.min.js#L3
