### ISSUE TITLE
Add all google fonts 

### ISSUE THREAD

**Issue by volkandkaya** [cdnjs/packages#497]
**Library name:** Google Fonts

**Library license (include link):** https://github.com/google/fonts#licensing

**Library source (NPM package or Git repo):** https://github.com/google/fonts

I'm already using webfont from this CDN. If it also came with all the fonts and they were cached (google fonts don't seem to be cached and require downloading) I believe this would become the default option for google fonts.

**Comment by xtuc** [comment]
> google fonts don't seem to be cached and require downloading

how did you notice that?

`fonts.gstatic.com` seems to be served with the right caching headers

**Comment by volkandkaya** [comment]
@xtuc please check https://gtmetrix.com/reports/churn.versoly.page/bJOqwcky report.

Tons of stackoverflow etc where the advice is to download the fonts locally.

**Comment by MattIPv4** [comment]
That report shows nothing wrong -- Google know what they're doing with serving fonts.

That being said, I think it makes sense for us to host more fonts, we already have a few. https://github.com/google/fonts is not a source we can use though, as it does not have tags (see https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#configuring-library-auto-update).

If you have any other suggestions for a tagged git source, or NPM package, let us know and we can look at adding it to cdnjs :)

**Comment by volkandkaya** [comment]
@MattIPv4 "There are 2 static components without a far-future expiration date". Is the main issue.

**Comment by MattIPv4** [comment]
Yup, the Google fonts URL you call will never have strong caching on it as the response is customised for different browsers, different UAs, different regions etc.

The resources it then uses in the CSS response are properly cached though, just not that initial CSS file.
