### ISSUE TITLE
ExtJS 7.0.0 GPL

### ISSUE THREAD

**Issue by mmsmdali** [cdnjs/packages#513]
**Library name:** ExtJS 7.0.0 GPL

**Library JSON file link:**

**Library source (NPM package or Git repo):**
[GPL Direct (Zip) download](https://www.sencha.com/legal/GPL)
[NPM Access](https://sencha.myget.org) (Sencha ExtGen v7.0.0 GPL Edition - The Ext JS code generator). 

**Files to include:**

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Custom NPM registries and direct downloads are out-of-scope for cdnjs. A package either needs a tagged git repo, or an NPM package on npmjs.com, to be considered for being added to cdnjs.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
