### ISSUE TITLE
Add: @deepstream/client

### ISSUE THREAD

**Issue by yasserf** [cdnjs/packages#523]
Hello!

The client has 200 stars, but due to the microrepo distribution the server has most starts at 6.7k

**Library name:** @deepstream/client
**Library license (include link):** [Apache License, Version 2.0](https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/LICENSE)
Website: [deepstream.io](https://deepstream.io)

**Library source (NPM package or Git repo):** [github](https://github.com/deepstreamIO/deepstream.io-client-js), [npm](https://www.npmjs.com/package/@deepstream/client)

**Comment by yasserf** [comment]
Probably worth mentioning the previous version was @deepstream.io-client-js but that got moved when we switch to an OS npm org

**Comment by MattIPv4** [comment]
We already have https://cdnjs.com/libraries/deepstream.io-client-js (https://github.com/cdnjs/packages/blob/master/packages/d/deepstream.io-client-js.json).

Is the intention of this request just to change the auto-update target to `@deepstream/client`?

**Comment by yasserf** [comment]
Both npm have different versions, they package itself wasn’t renamed.

Deepstream.io-client-js contains all releases before 2019.
 @deepstream/client since.

Intention is to add @deepstream/client to keep that distinction

Thanks!
