### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by mwaqas711625** [cdnjs/packages#542]
some cdn  and like file not found in your l libraries  please update and keep it maintain its working smoothly

i am trying the found html2canvas cdn and its library last 1 hours but i connot found it

**Comment by MattIPv4** [comment]
Hi @mwaqas711625,

Could you share which URLs are working for you on the CDN that you are expecting to be working?

**Comment by mwaqas711625** [comment]
Http://cndjs.cloudflare.com/ajac/libs/html2canvas/0.4.1/html2canvas.min.js

**Comment by MattIPv4** [comment]
It looks like you have a few typos in that URL, with them corrected the resource loads just fine: https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js

**Comment by mwaqas711625** [comment]
http://cndjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js

**Comment by MattIPv4** [comment]
No further progress, closing
