### ISSUE TITLE
[Update Request] Update: echarts 5.0.0 from NPM

### ISSUE THREAD

**Issue by plainheart** [cdnjs/packages#548]
**Library name:** echarts

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/e/echarts.json

**Library source (NPM package or Git repo):** https://www.npmjs.com/package/echarts/v/5.0.0

**Files to include:** dist, i18n, theme

Hi, dear team,

Recently, to avoid missing some formal versions, we have moved the source of ECharts to NPM from GitHub in #512.

The current latest version 5.0.0 of ECharts in cdnjs was previously fetched from the GitHub release, but it's different from the latest version on NPM. (Some RC versions were released on GitHub with the tag 5.0)
So the files in cdnjs are not the same as those in NPM now. I'm afraid this will probably mislead some users who are using our cdnjs service.

Here I'm wondering if we can update the distribution files of ECharts 5.0.0 again from NPM?
Thanks a lot!

**Comment by MattIPv4** [comment]
Assets already on cdnjs will never be updated or removed, this violates the integrity of the CDN and those assets.

**Comment by plainheart** [comment]
All right. Still thank you for making me informed, anyway. I feel sorry for this request.
