### ISSUE TITLE
Update: modernizr

### ISSUE THREAD

**Issue by cxF9Au4t** [cdnjs/packages#560]
**Library name:** modernizr

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/m/modernizr.json

**Library source (NPM package or Git repo):** https://www.npmjs.com/package/modernizr

**Files to include:** `modernizr.min.js, modernizr.js`

The latest version is 3.11.4
The version of cdnjs is stuck at 2.8.3

**Comment by MattIPv4** [comment]
Modernizr no longer includes a pre-built version on GitHub or via NPM, so we cannot pull down new versions for cdnjs.
