### ISSUE TITLE
Bank Card data steeling

### ISSUE THREAD

**Issue by Zuluparaszt** [cdnjs/packages#573]
In our website this has been collecting our customers data:

https://gerennorodemi.gq/order/index.php?usr=34683218

And in the code:

"https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/md5.min.js"

**Comment by MattIPv4** [comment]
https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/md5.min.js is a valid asset that has not been compromised.

Please report phishing sites to the host of them, in this case, Cloudflare: https://www.cloudflare.com/abuse/form

**Comment by Zuluparaszt** [comment]
ok thank you!
