### ISSUE TITLE
[Request] Add ImageMapster

### ISSUE THREAD

**Issue by MonsieurV** [cdnjs/packages#587]
**Library name:** ImageMapster
**Git repository url:** https://github.com/jamietre/imagemapster
**npm package url(optional):** -
**License(s):** MIT
**Official homepage:** http://www.outsharked.com/imagemapster/
**Wanna say something? Leave message here:** Would be handy!

(I can prepare a PR in the following days if that helps)

**Comment by techfg** [comment]
Awesome news @MattIPv4, thank you for the prompt attention to this!!
