### ISSUE TITLE
Update: bootstrap-icons

### ISSUE THREAD

**Issue by cocxtrash** [cdnjs/packages#600]
**Library name:** bootstrap-icons

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/b/bootstrap-icons.json

**Library source (NPM package or Git repo):** https://github.com/twbs/icons

**Files to include:** bootstrap-icons.css

**Extra Info:** 
https://cdnjs.com/libraries/bootstrap-icons
https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css
https://icons.getbootstrap.com/

**Comment by MattIPv4** [comment]
Please use the update request template correctly to request a library be updated with new files for future versions.

**Comment by cocxtrash** [comment]
Sorry. I'm noob at this. do i edit this issue? or create a new one? what is 'Library JSON file link" ?

**Comment by MattIPv4** [comment]
You can edit this issue, the JSON link will be to the bootstrap-icons JSON config file in this repository.

**Comment by cocxtrash** [comment]
> 
> 
> You can edit this issue, the JSON link will be to the bootstrap-icons JSON config file in this repository.

Hi, Edited It. Is it ok now?

**Comment by cocxtrash** [comment]
Hi, You closed the issue means it solved. But the **css** file is still not included. I don't understand, am I looking in the wrong place?

**Comment by MattIPv4** [comment]
We never modify existing versions, you will need to wait until the next version is released, at which point we'll include the new files.
