### ISSUE TITLE
[Request Update] jquery-validate

### ISSUE THREAD

**Issue by lastingrewind** [cdnjs/packages#602]
**Library name:** jquery-validation

**Library JSON file link:** [https://github.com/jquery-validation/jquery-validation/blob/master/package.json](https://github.com/jquery-validation/jquery-validation/blob/master/package.json)

**Library source (NPM package or Git repo):** [https://github.com/jquery-validation/jquery-validation](https://github.com/jquery-validation/jquery-validation)

**Files to include:** [https://github.com/jquery-validation/jquery-validation/blob/master/src/core.js](https://github.com/jquery-validation/jquery-validation/blob/master/src/core.js)

**Comment by lastingrewind** [comment]
Any updates on this? I can only get version 1.19.2.

**Comment by MattIPv4** [comment]
This was [merged on the 27th of Jan](https://github.com/cdnjs/packages/pull/603). [No new version has been released since then](https://github.com/jquery-validation/jquery-validation/releases), so there have been no new versions for cdnjs to pull.
