### ISSUE TITLE
Dropzone.js 5.6.0 is not in the library

### ISSUE THREAD

**Issue by Allianzcortex** [cdnjs/packages#605]
**Library name:** Dropzone.js

**Library license (include link):**  MIT 

**Library source (NPM package or Git repo):** NPM

Link : https://cdnjs.com/libraries/dropzone/5.6.0

If you check the cdn.js, you will find that package is not loaded actually : 

![image](https://user-images.githubusercontent.com/7290780/106013548-ee092300-6092-11eb-8ee6-0add2bd2fc1e.png)

While version 5.6.1 and version 5.7.0 are available : 

![image](https://user-images.githubusercontent.com/7290780/106013665-0b3df180-6093-11eb-8ffb-d08a861741b1.png)

![image](https://user-images.githubusercontent.com/7290780/106013728-1e50c180-6093-11eb-9297-0add522f67f1.png)

**Comment by MattIPv4** [comment]
This is an issue with the downstream package, not something we can resolve. Version 5.6.0 did and still does not contain the JS file:

```
npm i dropzone@5.6.0

...

tree node_modules/dropzone/dist

node_modules/dropzone/dist
├── basic.css
├── dropzone.css
├── dropzone.js.map
└── min
    ├── basic.min.css
    └── dropzone.min.css

1 directory, 5 files
```

**Comment by Allianzcortex** [comment]
@MattIPv4 LOL . see the log here : https://github.com/enyo/dropzone/blame/10b65490a41232a76cc70ef40bb1b0a826a99eaf/CHANGELOG.md#L28
