### ISSUE TITLE
Accessibility issue: Voiceover is reading (___)(___)(____) on the phone number field with masking on that field

### ISSUE THREAD

**Issue by chandra9424** [cdnjs/packages#606]
[Accessibility][Screen Reader][Required Fields] When placing focus in an affected required field on the form that the field is required. This incorrectly implies to screen reader users that input for the affected fields is optional. And dose not read label of associated field. It reads only  (___)(___)(____) "parenthesis underscore underscore  underscore  parenthesis" like that.

Affected browser: MAC safari browser.
Affected screen reader tool : Mac voiceover.
Affected Field(s): Any masking field
Affected WCAG 2.1 Guideline(s): 1.3.1 Info and Relationships3.3.2 Labels or Instructions

**Library name:** jquery.maskedinput
**Library JSON file link:** https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js
**Library source (NPM package or Git repo):** https://github.com/digitalBush/jquery.maskedinput
**Files to include:** NA

**Comment by MattIPv4** [comment]
We do not provide support for libraries hosted on cdnjs, you will need to contact the maintainers of that library.
