### ISSUE TITLE
Change to Bootstrap Icons to include font folder

### ISSUE THREAD

**Issue by richardwo** [cdnjs/packages#619]
URL https://cdnjs.com/libraries/bootstrap-icons
Since version 1.2.0 a font folder has been added to the package containing bootstrap-icons.css
Please can this folder be added to cdnjs.

**Comment by MattIPv4** [comment]
Change was made in https://github.com/cdnjs/packages/pull/604 -- the font folder should be present when the next bootstrap-icons version is released.
