### ISSUE TITLE
Update: jquery-validation.js

### ISSUE THREAD

**Issue by TheDestinyGroup** [cdnjs/packages#632]
Library name: jquery-validation.js

Library JSON file link: https://github.com/jquery-validation/jquery-validation/blob/master/validation.jquery.json

Library source (NPM package or Git repo): https://www.nuget.org/packages/jQuery.Validation, https://github.com/jquery-validation/jquery-validation

Files to include: jquery.validate.min.js, jquery.validate.js, additional-methods.min.js, additional-methods.js, localization/*

The latest version is 1.19.3, but cdnjs' version is 1.19.2

**Comment by MattIPv4** [comment]
We updated the config in #602/#603 -- no new version has yet been published since that config update so that bot has not yet been triggered to fetch a new version.
