### ISSUE TITLE
【Request】Please add "Ovine" lib

### ISSUE THREAD

**Issue by CareyToboo** [cdnjs/packages#654]
The **Ovine** project is a basic framework that provides a way to develop "website management system" mainly using JSON. In order for users to develop projects quickly, a large number of basic dependency packages are built-in. We used **WEBPACK DLL** to package some commonly used dependency packages in advance. Therefore, this part of the **DLL** file needs to be stored in the CDN for faster access.

Can CDNJS be used for such requirements? If CDNJS is available, we will provide an NPM package specifically for CDNJS storage, which can be synchronized with Ovine to automatically upgrade.

If CDNJS cannot be used, we will consider other options.

Looking forward to hearing from you ～

**Library name:** ovine

**Library license (include link):** MIT

**Library source (NPM package or Git repo):** https://github.com/CareyToboo/ovine

**Comment by MattIPv4** [comment]
👋 cdnjs does not support hosting DLL files, we focus on hosting files meant for the web -- you can find the full list of extensions we support at https://api.cdnjs.com/whitelist

**Comment by CareyToboo** [comment]
Thanks for such a quick reply.

What I said is not clear enough. I am talking about " [Webpack DllPlugin](https://webpack.js.org/plugins/dll-plugin/#root) ", the files that need to be hosted are not ".dll" files. They are all web asset files.  This is a screenshot of the files.

![image](https://user-images.githubusercontent.com/15522313/111093267-6fe5da80-8573-11eb-9540-b21d61c99262.png)

**Comment by MattIPv4** [comment]
That looks like normal webpack chunking -- should be fine :+1:

I assume there is a single consistent file that the user would include on their page to then load these chunked files in automatically?

**Comment by CareyToboo** [comment]
Yes, the "ovine app" project will automatically load this entry file, and then automatically load other chunk files.

**Comment by MattIPv4** [comment]
Sgtm, which NPM package do we need to target to get this consistent entry point file and the chunks? You seem to have missed that from the original issue

**Comment by CareyToboo** [comment]
We haven't put these files in the npm package yet.

We are going to put these chunk files into a subfolder of the npm package in the next version. For example: `node_moudles/@ovine-pkg-root-dir/env/.ovine/dll/0.0.1/somefiles-need-hosted.js|css`

Hope it can be converted to: `https://cdnjs.cloudflare.com/ajax/libs/ovine/0.0.1/filename.xxx`

Is this okay? If possible, we will release the version now.

**Comment by MattIPv4** [comment]
If you can get the files available in your NPM package, we can then work from there to establish if it will be logical to bring them in to cdnjs.

**Comment by CareyToboo** [comment]
I'm so sorry to reply to you now. Recently, I am preparing to put static assets files in the npm package.

npm package url:  https://www.npmjs.com/package/@ovine/init

The files that needs to be hosted is `@ovine/init/env/.ovine/static/dll/0.1.2-alpha.0/`

The files can be found in the newly released `v0.1.2-alpha.0`.  If you need any other information, please let me know. I can make changes in the next version. If all goes well, I will release the `v0.1.2` version.

Thanks very much for the support of cdnjs.

**Comment by MattIPv4** [comment]
We don't really have a way to target files that are in changing directory names, we'd expect files that we are looking to host to be in a consistent location that we can look for.

I'm also a bit concerned about whether or not this package makes sense to host on cdnjs, I'm not sure if it meets [our criteria for being considered a popular package](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines)?

**Comment by CareyToboo** [comment]
I found the ["jsdelivr cdn"](https://www.jsdelivr.com/features), it's what I want for my needs.
Anyway, thank you very much.
