### ISSUE TITLE
Update: gridmest

### ISSUE THREAD

**Issue by mestoness** [cdnjs/packages#655]
**Library name:** gridmest

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/g/gridmest.json

**Library source (NPM package or Git repo):** https://www.npmjs.com/package/gridmest

I request the removal of all versions except 1.0.13

**Comment by MattIPv4** [comment]
👋 cdnjs does not support the removal of libraries or existing versions, as this would be a breaking change for any users that rely on those files.
