### ISSUE TITLE
Add P5-Speech and other p5 libs

### ISSUE THREAD

**Issue by ErrorBot1122** [cdnjs/packages#661]
**Library name:** P5-Speech

**Library license (include link):** https://github.com/IDMNYU/p5.js-speech/blob/master/LICENSE

**Library source (NPM package or Git repo):** https://github.com/IDMNYU/p5.js-speech

it is on the p5 website but no CDN

Lib only: https://raw.githubusercontent.com/IDMNYU/p5.js-speech/master/lib/p5.speech.js

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
