### ISSUE TITLE
Tiny async pool

### ISSUE THREAD

**Issue by ConradKurth** [cdnjs/packages#673]
**Library name:** tiny-async-pool

**Library license (include link):** https://github.com/rxaviers/async-pool/blob/master/LICENSE-MIT

**Library source (NPM package or Git repo):** https://github.com/rxaviers/async-pool

**Comment by MattIPv4** [comment]
👋 All the files in `dist` and `lib` for this library rely on `require` statements which will not work with cdnjs as we host files designed to run in a web context. Please let me know if there is an alternative source available with web versions that we can serve, or feel free to close out this issue :)

**Comment by ConradKurth** [comment]
Ahhh! I see. I don't think there is but I will see if there is some alternatives. Thanks!
