### ISSUE TITLE
Recently updated/added libraries not detected

### ISSUE THREAD

**Issue by iChenLei** [cdnjs/packages#696]
## 1. user can't contribute to `cdnjs/packages` by local clone on `MacOS`.
![021-04-15 17 37 05](https://user-images.githubusercontent.com/14012511/114848367-3376fa00-9e11-11eb-8aba-761d97d19503.png)

### No mobx v6

<img src="https://user-images.githubusercontent.com/14012511/114848687-88b30b80-9e11-11eb-8a9c-0855b1016992.png" width="400px" />

![2021-04-15 17 40 24](https://user-images.githubusercontent.com/14012511/114848806-ab452480-9e11-11eb-80ff-35c3bc967554.png)

### No mobx-react v6 and v7

<img src="https://user-images.githubusercontent.com/14012511/114848715-8fda1980-9e11-11eb-9f63-59bd89f6e355.png" width="400px" />

![2021-04-15 17 40 53](https://user-images.githubusercontent.com/14012511/114848846-bb5d0400-9e11-11eb-8703-47fe6102e6e7.png)

### And can't found mobx-react-lite any version.
<img src="https://user-images.githubusercontent.com/14012511/114848729-96689100-9e11-11eb-838b-6dbfc55df2d3.png" width="400px" />

![2021-04-15 17 41 28](https://user-images.githubusercontent.com/14012511/114848927-d16ac480-9e11-11eb-8a30-7fecc21422df.png)

/cc @MattIPv4 @tc80

**Comment by MattIPv4** [comment]
cdnjs requires a case sensitive file system to work with -- see https://github.com/cdnjs/cdnjs/issues/3650. You can likely ignore the warning though unless you are actively modifying one of the case sensitive files, everything else will still work fine.

@tc80 @xtuc Any ideas why https://github.com/cdnjs/packages/blob/master/packages/m/mobx-react-lite.json hasn't been picked up by the bot?

**Comment by iChenLei** [comment]
Still not work, not only mobx relative package but also the same batch `PR` package(e.g. PubSub / responsive-tabs

**Comment by iChenLei** [comment]
Still not work, not only mobx relative package but also the same batch `PR` package(e.g. PubSub / responsive-tabs
@MattIPv4 @xtuc @tc80

**Comment by MattIPv4** [comment]
We're aware and looking into it, you don't need to keep mentioning us all 👍

**Comment by iChenLei** [comment]
Thanks for `cdnjs` team, now it works. ❤️
