### ISSUE TITLE
chartjs-plugin-annotation is missing latest version (1.0.0)

### ISSUE THREAD

**Issue by KoalaBear84** [cdnjs/packages#697]
**Library name:** chartjs-plugin-annotation

**Library JSON file link:** https://github.com/cdnjs/packages/blob/master/packages/c/chartjs-plugin-annotation.json

**Library source (NPM package or Git repo):** https://github.com/chartjs/chartjs-plugin-annotation

**Files to include:** I have no idea how this part works, as it looks like it needs to be build? Maybe the "dist" folder is removed?

See: https://github.com/chartjs/chartjs-plugin-annotation/blob/master/package.json

**Comment by kurkle** [comment]
Library is released through npmjs: https://www.npmjs.com/package/chartjs-plugin-annotation

**Comment by KoalaBear84** [comment]
Maybe the package definition could be changed to get it from npm instead.

**Comment by KoalaBear84** [comment]
The issue is now resolved through the PR, thanks!
