### ISSUE TITLE
Add: Mootable Hashmap

### ISSUE THREAD

**Issue by jackmoxley** [cdnjs/packages#729]
### Library name

mootable-hashmap

### Library license

https://github.com/mootable/hashmap/blob/master/LICENSE

### Library source

https://github.com/mootable/hashmap/

**Comment by jackmoxley** [comment]
Hi @MattIPv4 it may be too soon, but I couldn't see it being synced into cdnjs/cdnjs, have I made a mistake somewhere?

**Comment by MattIPv4** [comment]
👋 We have ongoing maintenance with the auto-update functionality of cdnjs currently -- You can follow along on our status page for when the maintenance will conclude: https://status.cdnjs.com/
