### ISSUE TITLE
Update: layer

### ISSUE THREAD

**Issue by kangkk** [cdnjs/packages#736]
### Library name

layer

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/l/layer.json

### Library source

https://github.com/sentsin/layer

### Files to include

我看到 https://status.cdnjs.com/ 上面的 Auto-update bot 在维护状态，所以 layer 才没有更新么？

**Comment by MattIPv4** [comment]
👋 We have ongoing maintenance with the auto-update functionality of cdnjs currently -- this version was released since the maintenance started, and so our auto-update logic hasn't been running to detect it. You can follow along on our status page for when the maintenance will conclude: https://status.cdnjs.com/

**Comment by VDovidaytis-HORIS** [comment]
Hello! I have the same auto-update issue. How long will auto-update service maintenance take?

**Comment by MattIPv4** [comment]
👋 I realise that this maintenance has been going on for over a month now and we still have many packages that are not being updated by the new system that is being worked on, and I can only apologise for that -- the team is working hard to get the new auto-update system up and running with all the new packages as fast as we can.

@xtuc do you think you'd be able to share insight on when you expect the new auto-update system to be live and supporting all packages on NPM/Git again?

**Comment by xtuc** [comment]
all npm packages should be auto-updateing this week again. git support is still being implemented

**Comment by MattIPv4** [comment]
The latest version is available on the CDN
