### ISSUE TITLE
Add: automerge

### ISSUE THREAD

**Issue by inventivejon** [cdnjs/packages#742]
### Library name

automerge

### Library license

https://github.com/automerge/automerge/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/automerge

**Comment by MattIPv4** [comment]
👋 This library does not appear to distribute a pre-bundled version -- the files they distribute make use of `require` calls which only work in a Node.js environment and not in a browser.

**Comment by inventivejon** [comment]
Just compiled a pre bundled version yesterday for use in Blazor. Would it help if I deliver that one or does it need to be hosted?

**Comment by MattIPv4** [comment]
It will need to be distributed on npm or git -- I would suggest working with the authors of the original library to have a pre-bundled version distributed as part of their releases.

**Comment by inventivejon** [comment]
Sure, I will write here as soon as it is done.

**Comment by MattIPv4** [comment]
No progress, closing
