### ISSUE TITLE
fullPage.js not on latest version?

### ISSUE THREAD

**Issue by alvarotrigo** [cdnjs/packages#751]
https://cdnjs.com/libraries/fullPage.js/3.1.0
Shows 3.1.0 as the latest.

While npm shows 3.1.1:
https://www.npmjs.com/package/fullpage.js

As well as fullpage.js github releases pages:
https://github.com/alvarotrigo/fullPage.js/releases

And it has been like this for a month?

**Comment by MattIPv4** [comment]
Version is now available: https://cdnjs.com/libraries/fullPage.js/3.1.1

**Comment by alvarotrigo** [comment]
Thanks! 👍
