### ISSUE TITLE
hls.js does not update anymore

### ISSUE THREAD

**Issue by olafcm** [cdnjs/packages#762]
### Library name

hls.js

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/h/hls.js.json

### Library source

https://www.npmjs.com/package/hls.js

### Files to include

hls.*

**Comment by MattIPv4** [comment]
The config looks to be valid: [glob tool](https://www.digitalocean.com/community/tools/glob#?comments=true&glob=dist%2F%2A%2A%2F%21%28%2A-demo.%2A%29&matches=false&tests=%2F%2F%20Imported%20from%20hls.js%20NPM%20package&tests=LICENSE&tests=src%2Fempty.js&tests=dist%2Fhls-demo.js&tests=dist%2Fhls.js&tests=dist%2Fhls.light.js&tests=dist%2Fhls.light.min.js&tests=dist%2Fhls.min.js&tests=package.json&tests=dist%2Fhls-demo.js.map&tests=dist%2Fhls.js.map&tests=dist%2Fhls.light.js.map&tests=dist%2Fhls.light.min.js.map&tests=dist%2Fhls.min.js.map&tests=README.md&tests=src%2Fremux%2Faac-helper.ts&tests=src%2Fdemux%2Faacdemuxer.ts&tests=src%2Fcontroller%2Fabr-controller.ts&tests=src%2Fdemux%2Fadts.ts&tests=src%2Fcrypt%2Faes-crypto.ts&tests=src%2Fcrypt%2Faes-decryptor.ts&tests=src%2Futils%2Fattr-list.ts&tests=src%2Fcontroller%2Faudio-stream-controller.ts&tests=src%2Fcontroller%2Faudio-track-controller.ts&tests=src%2Fdemux%2Fbase-audio-demuxer.ts&tests=src%2Fcontroller%2Fbase-playlist-controller.ts&tests=src%2Fcontroller%2Fbase-stream-controller.ts&tests=src%2Futils%2Fbinary-search.ts&tests=src%2Fcontroller%2Fbuffer-controller.ts&tests=src%2Futils%2Fbuffer-helper.ts&tests=src%2Fcontroller%2Fbuffer-operation-queue.ts&tests=src%2Ftypes%2Fbuffer.ts&tests=src%2Fcontroller%2Fcap-level-controller.ts&tests=src%2Futils%2Fcea-608-parser.ts&tests=src%2Fdemux%2Fchunk-cache.ts&tests=src%2Futils%2Fchunker.ts&tests=src%2Futils%2Fcodecs.ts&tests=src%2Ftypes%2Fcomponent-api.ts&tests=src%2Fconfig.ts&tests=src%2Futils%2Fcues.ts&tests=src%2Fcrypt%2Fdecrypter.ts&tests=src%2Fdefine-plugin.d.ts&tests=src%2Ftypes%2Fdemuxer.ts&tests=src%2Futils%2Fdiscontinuities.ts&tests=src%2Fdemux%2Fdummy-demuxed-track.ts&tests=src%2Fcontroller%2Feme-controller.ts&tests=src%2Ferrors.ts&tests=src%2Fevents.ts&tests=src%2Ftypes%2Fevents.ts&tests=src%2Futils%2Fewma-bandwidth-estimator.ts&tests=src%2Futils%2Fewma.ts&tests=src%2Fdemux%2Fexp-golomb.ts&tests=src%2Fcrypt%2Ffast-aes-key.ts&tests=src%2Futils%2Ffetch-loader.ts&tests=src%2Fcontroller%2Ffps-controller.ts&tests=src%2Fcontroller%2Ffragment-finders.ts&tests=src%2Floader%2Ffragment-loader.ts&tests=src%2Fcontroller%2Ffragment-tracker.ts&tests=src%2Ftypes%2Ffragment-tracker.ts&tests=src%2Floader%2Ffragment.ts&tests=src%2Fcontroller%2Fgap-controller.ts&tests=src%2Ftypes%2Fgeneral.ts&tests=src%2Futils%2Fhex.ts&tests=dist%2Fhls.js.d.ts&tests=src%2Fhls.ts&tests=src%2Fcontroller%2Fid3-track-controller.ts&tests=src%2Fdemux%2Fid3.ts&tests=src%2Futils%2Fimsc1-ttml-parser.ts&tests=src%2Fis-supported.ts&tests=src%2Floader%2Fkey-loader.ts&tests=src%2Fcontroller%2Flatency-controller.ts&tests=src%2Fcontroller%2Flevel-controller.ts&tests=src%2Floader%2Flevel-details.ts&tests=src%2Fcontroller%2Flevel-helper.ts&tests=src%2Floader%2Flevel-key.ts&tests=src%2Ftypes%2Flevel.ts&tests=src%2Floader%2Fload-stats.ts&tests=src%2Ftypes%2Floader.ts&tests=src%2Futils%2Flogger.ts&tests=src%2Floader%2Fm3u8-parser.ts&tests=src%2Ftypes%2Fmedia-playlist.ts&tests=src%2Futils%2Fmediakeys-helper.ts&tests=src%2Futils%2Fmediasource-helper.ts&tests=src%2Fdemux%2Fmp3demuxer.ts&tests=src%2Fremux%2Fmp4-generator.ts&tests=src%2Fremux%2Fmp4-remuxer.ts&tests=src%2Futils%2Fmp4-tools.ts&tests=src%2Fdemux%2Fmp4demuxer.ts&tests=src%2Fdemux%2Fmpegaudio.ts&tests=src%2Fpolyfills%2Fnumber.ts&tests=src%2Futils%2Foutput-filter.ts&tests=src%2Fremux%2Fpassthrough-remuxer.ts&tests=src%2Fperformance%2Fperformance-monitor.ts&tests=src%2Floader%2Fplaylist-loader.ts&tests=src%2Ftypes%2Fremuxer.ts&tests=src%2Fdemux%2Fsample-aes.ts&tests=src%2Fcontroller%2Fstream-controller.ts&tests=src%2Fcontroller%2Fsubtitle-stream-controller.ts&tests=src%2Fcontroller%2Fsubtitle-track-controller.ts&tests=src%2Ftask-loop.ts&tests=src%2Futils%2Ftexttrack-utils.ts&tests=src%2Futils%2Ftime-ranges.ts&tests=src%2Fcontroller%2Ftimeline-controller.ts&tests=src%2Futils%2Ftimescale-conversion.ts&tests=src%2Ftypes%2Ftrack.ts&tests=src%2Fdemux%2Ftransmuxer-interface.ts&tests=src%2Fdemux%2Ftransmuxer-worker.ts&tests=src%2Fdemux%2Ftransmuxer.ts&tests=src%2Ftypes%2Ftransmuxer.ts&tests=src%2Fdemux%2Ftsdemuxer.ts&tests=src%2Ftypes%2Ftuples.ts&tests=src%2Futils%2Ftyped-array.ts&tests=src%2Ftypes%2Fvtt.ts&tests=src%2Futils%2Fvttcue.ts&tests=src%2Futils%2Fvttparser.ts&tests=src%2Futils%2Fwebvtt-parser.ts&tests=src%2Futils%2Fxhr-loader.ts)

@xtuc can you take a look at this from the bot's side to see if anything looks wrong?

**Comment by xtuc** [comment]
Forced an update and  latest version is online: https://cdnjs.com/libraries/hls.js/1.0.7.

**Comment by olafcm** [comment]
Thank you guys!
