### ISSUE TITLE
Add: tmi.js (browser build)

### ISSUE THREAD

**Issue by sslanec** [cdnjs/packages#763]
### Library name

tmi.js

### Library license

https://github.com/tmijs/tmi.js/blob/master/LICENSE

### Library source

https://github.com/tmijs/tmi.js/releases/latest

**Comment by MattIPv4** [comment]
👋 For us to be able to add libraries, they either need to have the files available in a git repository that is appropriately tagged for versions, or available in an NPM package.

With tmi.js, it appears that they only distribute the pre-build browser release via the releases page, and it is not available in the tagged git repo, nor in the NPM package, so we're unable to add it.

**Comment by sslanec** [comment]
Ah, I see. Didn't realize that. My apologies.
