### ISSUE TITLE
dash.js does not update anymore

### ISSUE THREAD

**Issue by olafcm** [cdnjs/packages#766]
### Library name

dashjs

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/d/dashjs.json

### Library source

https://www.npmjs.com/package/dashjs

### Files to include

dash.*.js

**Comment by MattIPv4** [comment]
cdnjs has the latest version available, this is updating just fine.

**Comment by olafcm** [comment]
Great, thanks!!
