### ISSUE TITLE
Update: Alpine.js

### ISSUE THREAD

**Issue by chriscoyier** [cdnjs/packages#769]
### Library name

alpine

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/a/alpinejs.json

### Library source

https://www.npmjs.com/package/alpinejs

### Files to include

You can see the search results here:
https://cdnjs.com/libraries/alpinejs

Example JSON search results...

```
{
  "hits": [
    {
      "name": "alpinejs",
      "filename": "alpine.js",
      "description": "A rugged, minimal framework for composing JavaScript behavior in your markup.",
      "version": "3.2.1",
      "fileType": "js",
```

The problem is there is no `filename` of `alpine.js`. The filenames are...

- cdn.js
- module.cjs.js
- module.esm.js

(and minified versions). 

I'd wish the Algolia API would return the `cdn.js` filename.

**Comment by MattIPv4** [comment]
This is now live: https://api.cdnjs.com/libraries?search=alpine&fields=latest,filename,sri :)

**Comment by chriscoyier** [comment]
Much obliged.
