### ISSUE TITLE
Add: file-type

### ISSUE THREAD

**Issue by ThHenrique** [cdnjs/packages#774]
### Library name

file-type

### Library license

https://github.com/sindresorhus/file-type/blob/main/license

### Library source

https://www.npmjs.com/package/file-type

**Comment by MattIPv4** [comment]
Unfortunately, it looks like the library doesn't provide a bundled version of itself, only a Node.js version. The Node.js version relies on `require` calls which won't in a browser, so we can't add this to cdnjs.
