### ISSUE TITLE
Missing some webfonts in Fontawesome libraries

### ISSUE THREAD

**Issue by iamr8** [cdnjs/packages#821]
[Fontawesome 5.15.4](https://cdnjs.com/libraries/font-awesome) Doesn't have *.woff2 fonts, whereas it is exists in 5.15.3 version

**Comment by JonaBrackenwood** [comment]
Same problem is occurring with bootstrap-icons woff2-font, the file is shown with the warning "This file type is not whitelisted on the CDN and will not be available."

**Comment by MattIPv4** [comment]
> Same problem is occurring with bootstrap-icons woff2-font, the file is shown with the warning "This file type is not whitelisted on the CDN and will not be available."

`woff2` is a whitelisted file extension -- where are you seeing this message @JonaBrackenwood?

**Comment by MattIPv4** [comment]
> Fontawesome 5.15.4 Doesn't have *.woff2 fonts, whereas it is exists in 5.15.3 version

@xtuc this doesn't seem right, the distributed package definitely contains the `woff2` files, and our auto-update config should catch them?

```
ls node_modules/@fortawesome/fontawesome-free/webfonts | grep "woff2"
fa-brands-400.woff2
fa-regular-400.woff2
fa-solid-900.woff2

npm view @fortawesome/fontawesome-free version
5.15.4
```

https://github.com/cdnjs/packages/blob/200a5ca1dcce7fa33f672add9eb77973a0b11747/packages/f/font-awesome.json#L26

**Comment by MattIPv4** [comment]
Oh, I see the warning now -- @xtuc it looks like the `woff2` extension is just being dropped from files?

![image](https://user-images.githubusercontent.com/12371363/129044216-66b3740b-5af5-4edf-abe9-e0b09b96a63b.png)
![image](https://user-images.githubusercontent.com/12371363/129044264-46d4037e-1b87-4baa-9421-4cf1a11c2257.png)

**Comment by MattIPv4** [comment]
👋 Hey folks, just to give an update here -- these files are available on the CDN, if you add the `woff2` extension they do return the expected files, so it seems this is an issue purely with our API and website for some reason not having the extension present. The team are looking into it 👍

**Comment by TheDestinyGroup** [comment]
Hi,

This issue is also affecting the installing and updating of client libraries in Visual Studio projects via the Package Manager. 

When installing/updating client libraries the woff2 files aren't listed as part of the package.

Les

**Comment by MattIPv4** [comment]
This is as resolved as we're going to get it. We've fixed the bug that was causing the woff2 extensions to be missing in the API data. Unfortunately, our API response for specific versions are marked as immutable, so although the source data now has the woff2 extensions, that API may still report them as missing. These files are available on the CDN though, and have always been.
