### ISSUE TITLE
Request Addition of Library

### ISSUE THREAD

**Issue by Niresh12495** [cdnjs/packages#823]
I request addition of Library
https://github.com/Niresh12495/LazyAdsense

Here are the distributions

**Comment by MattIPv4** [comment]
Please fill out the proper form that you are prompted to fill out for requesting a new library when creating an issue: https://github.com/cdnjs/packages/issues/new?assignees=&labels=%F0%9F%8F%B7+Library+Request&template=library-request.yml&title=Add%3A+xxx
