### ISSUE TITLE
Update: bootstrap-select v2.0.0-beta1

### ISSUE THREAD

**Issue by jecarr** [cdnjs/packages#828]
### Library name

bootstrap-select

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/b/bootstrap-select.json

### Library source

https://www.npmjs.com/package/bootstrap-select

### Files to include

(Sorry if pedantic! but) suggesting to remove all in dist; this is because:

- According to the codebase, v2.0.0 is still in development (snapappointments/bootstrap-select#2228)
- Currently, if someone uses the cdnjs links for this version, they get v1.6.3 from 2015 as this tag exists in the repo https://github.com/snapappointments/bootstrap-select/tree/v2.0.0-beta1 
- Both [NPM](https://www.npmjs.com/package/bootstrap-select) and [jsDelivr](https://www.jsdelivr.com/package/npm/bootstrap-select) omit v2.0.0 in their lists (and just have v1.13.18 and v.14.0-beta2 as per the [repo's latest tags](https://github.com/snapappointments/bootstrap-select/tags))

Thanks! (I've found cdnjs really helpful 🎉)

**Comment by MattIPv4** [comment]
👋 Unfortunately it is not possible for cdnjs to remove or modify versions that have already been published on the CDN. Removing a version would be a complete breaking change for anyone that happens to be using it, and modifying assets in the version would be a breaking change for anyone using SRI (which everyone should be!).
