### ISSUE TITLE
Update: bootstrap-datetimepicker

### ISSUE THREAD

**Issue by Eonasdan** [cdnjs/packages#841]
### Library name

bootstrap-datetimepicker

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/b/bootstrap-datetimepicker.json

### Library source

https://github.com/Eonasdan/tempus-dominus/releases/tag/v6-alpha1

### Files to include

dist/css/tempus-dominus.css
dist/js/tempus-dominus.js
dist/jQuery-provider.js

**Comment by Eonasdan** [comment]
I've renamed my repo and have just release an alpha version.

**Comment by MattIPv4** [comment]
I've created a PR to add your package under its new name, and update the existing package under the old name to update from the renamed repo as well. Lmk if you think a different approach should be taken.

**Comment by Eonasdan** [comment]
Looks good to me. That's probably the best path forward. After these get in I'll look at creating a "tutorial" for the existing one to let people know of the change there as well.

There's also this package: https://cdnjs.com/libraries/eonasdan-bootstrap-datetimepicker which appears to be a duplicate.

I just looked at https://cdnjs.com/libraries/bootstrap-datetimepicker

![image](https://user-images.githubusercontent.com/1006516/132226121-0f201904-9052-4b24-b0ca-8169650da586.png)

Hopefully the pr fixes this right? Definitely not the right files.
