### ISSUE TITLE
Add: dpath for Brython

### ISSUE THREAD

**Issue by ghost** [cdnjs/packages#874]
### Library name

brython-dpath

### Library license

https://github.com/dpath-maintainers/dpath-python/blob/master/LICENSE.txt

### Library source

https://gist.github.com/brianmingus2/f30ddc9dbd461e3d50814e77c3e9267e

**Comment by brianmingus2** [comment]
Brython has a package manager called brip which allows you to prepare python modules to be included via a javascript script tag.

I have packaged python-dpath for Brython here: https://github.com/dpath-maintainers/dpath-python

We can use this library as the starting point for Brython support in CDNJS.

**Comment by MattIPv4** [comment]
👋 We cannot use a gist as a source for a package. It either needs to be in a git-tagged repo, or published on NPM
