### ISSUE TITLE
Update: jquery.balloon.js 1.1.2

### ISSUE THREAD

**Issue by toddwhaley** [cdnjs/packages#888]
### Library name

jquery.balloon.js

### Library JSON file

https://github.com/urin/jquery.balloon.js/blob/master/package.json

### Library source

https://www.npmjs.com/package/jquery-balloon-js

### Files to include

- jquery-balloon-js

**Comment by toddwhaley** [comment]
As you can see here, the cdnjs link is serving up the wrong version:
https://cdnjs.cloudflare.com/ajax/libs/jquery-balloon-js/1.1.2/jquery.balloon.min.js
It's sending v1.0.3 when it should be v1.1.2:
https://github.com/urin/jquery.balloon.js/releases/tag/1.1.2

**Comment by MattIPv4** [comment]
👋 Unfortunately, we cannot change versions that are already published on the CDN. This library is set to auto-update from NPM, and pulling the package we can see that in their 1.1.2 release the file headers reference 1.0.3, so this is an issue outside of our control:

```
npm i jquery-balloon-js

npm ls jquery-balloon-js
test@1.0.0 /Users/mattcowley/Downloads/test
└── jquery-balloon-js@1.1.2

cat node_modules/jquery-balloon-js/jquery.balloon.js 
/**
 * Hover balloon on elements without css and images.
 *
 * Copyright (c) 2011 Hayato Takenaka
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 * @author: Hayato Takenaka (https://urin.github.io)
 * @version: 1.0.3 - 2016/07/02
**/
...
```

**Comment by MattIPv4** [comment]
No further progress, closing.
