### ISSUE TITLE
Add: fs-tpp-api

### ISSUE THREAD

**Issue by pejobo** [cdnjs/packages#909]
### Library name

fs-tpp-api

### Library license

http://www.apache.org/licenses/LICENSE-2.0.html

### Library source

https://www.npmjs.com/package/fs-tpp-api

**Comment by MattIPv4** [comment]
👋 Do you have a link to where this has its open-source code hosted? I'm struggling to find a GitHub repo for it.

**Comment by MattIPv4** [comment]
Hey! At present, unfortunately, it is, our schema requires a valid repository object for packages that are being added

**Comment by pejobo** [comment]
I will report back, give me a few days..

**Comment by pejobo** [comment]
This is the source repository: https://github.com/e-Spirit/ocm-snap
The name differs for historical reasons (TM)
