### ISSUE TITLE
Add: node-jose

### ISSUE THREAD

**Issue by kench** [cdnjs/packages#910]
### Library name

node-jose

### Library license

https://github.com/cisco/node-jose/blob/master/LICENSE

### Library source

https://www.npmjs.com/package/node-jose

**Comment by MattIPv4** [comment]
👋 The distributed version of this library is meant for Node.js, and makes many `require` calls. This will not work in a browser context, so I'm not sure it makes sense for us to host this on the CDN?

**Comment by MattIPv4** [comment]
No progress, closing.
