### ISSUE TITLE
Add: yup

### ISSUE THREAD

**Issue by wmhartl** [cdnjs/packages#925]
### Library name

yup

### Library license

https://github.com/jquense/yup/blob/master/LICENSE.md

### Library source

https://github.com/jquense/yup

**Comment by MattIPv4** [comment]
👋 The distributed version of this library is meant for Node.js, and makes many `require` calls. This will not work in a browser context, so I'm not sure it makes sense for us to host this on the CDN?

**Comment by wmhartl** [comment]
Ah, of course and fair enough! Wasn't thinking about that, just that it's heavily in use by react apps and is integrated with popular packages like react-hook-forms and formik and wanted to play with it in jsfiddle. Thanks for the quick response!
