### ISSUE TITLE
Add: cytoscape.js-view-utilities

### ISSUE THREAD

**Issue by Foorack** [cdnjs/packages#934]
### Library name

cytoscape.js-view-utilities

### Library license

https://github.com/iVis-at-Bilkent/cytoscape.js-view-utilities/blob/master/LICENSE

### Library source

https://www.npmjs.com/package/cytoscape-view-utilities

**Comment by MattIPv4** [comment]
👋 `src/index.js` relies on Node.js `require` calls to load the library -- this is not compatible with using a JS library on the web, which is the primary purpose that cdnjs serves.

Is there a version of this that is pre-bundled and would work on the web that should be used instead?

**Comment by MattIPv4** [comment]
No progress, closing.
