### ISSUE TITLE
Add: Vanilla Framework

### ISSUE THREAD

**Issue by 5u9** [cdnjs/packages#945]
### Library name

Vanilla Framework

### Library license

https://github.com/canonical-web-and-design/vanilla-framework/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/vanilla-framework

**Comment by MattIPv4** [comment]
👋 Looking at the NPM package, it appears that only the source SCSS files are distributed for this package, not any built CSS.

cdnjs does allow for SCSS files to be hosted, but we won't compile them, so you'd need to reference them from cdnjs in a context where you can still compile your own CSS.

Would you like us to still add this library?

**Comment by 5u9** [comment]
i just want cdnjs to decide it.

**Comment by MattIPv4** [comment]
Okay -- well given this is only distributing the SCSS and not any actual CSS, I don't think it overly makes sense to add this library at present.
