### ISSUE TITLE
Update: editor-md

### ISSUE THREAD

**Issue by lqccan** [cdnjs/packages#952]
### Library name

editor-md

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/e/editor-md.json

### Library source

https://github.com/pandao/editor.md.git

### Files to include

- css/editormd.css
- css/editormd.logo.css
- css/editormd.logo.min.css
- css/editormd.min.css
- css/editormd.preview.css
- css/editormd.preview.min.css
- editormd.amd.js
- editormd.amd.min.js
- editormd.json
- editormd.min.js

**Comment by MattIPv4** [comment]
👋 I'm not sure what you're requesting here -- the latest version of this package is 1.5.0 which was released many years ago, and cdnjs has available.

The config was updated here to include CSS: https://github.com/cdnjs/packages/pull/947

A new version would need to be published for this to take effect.

**Comment by lqccan** [comment]
i can't find css on the cdnjs，so i updated the config by #947 ，but it not auto update。it look like need published a new
version？but the editor-md author is not me。so，how to add 1.5.0 css file to cdnjs？

**Comment by MattIPv4** [comment]
cdnjs does not modify existing versions of published libraries, so a new version of the library would need to be published for the updated config to take effect.

**Comment by lqccan** [comment]
ok thanks

**Comment by lqccan** [comment]
ok thanks
