### ISSUE TITLE
资源不稳定

### ISSUE THREAD

**Issue by swarm413** [cdnjs/packages#965]
https://lib.baomitu.com/twitter-bootstrap/4.4.0/css/bootstrap.min.css
显示Internal Server Error
无独有偶
前几天https://lib.baomitu.com/iGrowl/3.0.3/css/fonts/feather.css
也是这样，Internal Server Error，过一天就能用了
希望给一个回复
cdn不稳定确实影响页面正常显示以及用户体验

**Comment by MattIPv4** [comment]
👋 `lib.baomitu.com` is not operated by us, so unfortunately we really can't help here. You will need to reach out to the provider of that service to establish why you may be having issues with it.

**Comment by swarm413** [comment]
是的，发现问题之后才发现这些资源都是cdnjs维护的，我对你们无私奉献致以崇高的敬意
目前cdn已经换成了比较稳定的staticfile cdn
如果不是因为国内政策的原因，我确实考虑过直接用你们的资源
