### ISSUE TITLE
Update: g2plot

### ISSUE THREAD

**Issue by Libohan12** [cdnjs/packages#970]
### Library name

g2plot

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/g/g2plot.json

### Library source

https://www.npmjs.com/package/@antv/g2plot

### Files to include

- g2plot.min.js
- g2plot.min.js.map

**Comment by MattIPv4** [comment]
👋 cdnjs already has the latest version of this library -- 2.4.7 is available on [NPM](https://www.npmjs.com/package/@antv/g2plot) and via [cdnjs](https://cdnjs.com/libraries/g2plot).
