### ISSUE TITLE
Add: jquery-ui 1.30.0  to cdnjs-cloudflare

### ISSUE THREAD

**Issue by gtbu** [cdnjs/packages#974]
### Library name

jquery-ui 1.30.0

### Library license

https://github.com/jquery/jquery-ui/blob/main/LICENSE.txt   CC1

### Library source

https://github.com/jquery/jquery-ui/releases/tag/1.13.0

**Comment by pableu** [comment]
See #889.

**Comment by MattIPv4** [comment]
👋 As noted in #889, jQuery UI is not distributed in a way that cdnjs can pull in. We have asked their team to provide a distribution that we could use (git tags, or an NPM package).
