### ISSUE TITLE
Add: Pretendard Font Upload Request

### ISSUE THREAD

**Issue by kms0219kms** [cdnjs/packages#975]
### Library name

Pretendard

### Library license

https://github.com/orioncactus/pretendard/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/pretendard

**Comment by kms0219kms** [comment]
Files that should be hosted by default:
"dist/web/static/pretendard.css"
"dist/web/static/pretendard-dynamic-subset.css"
"dist/web/variable/pretendardvariable.css"

**Comment by kms0219kms** [comment]
Sorry, there are a lot of files that need to be hosted by default,
since this library is a library related to fonts, it requires many files.

**Comment by MattIPv4** [comment]
I believe I captured all the files needed with:

```
"@(static|variable)/*.css",
"@(static|variable)/**/*.@(woff|woff2)"
```

**Comment by kms0219kms** [comment]
> I believe I captured all the files needed with:
> 
> ```
> "@(static|variable)/*.css",
> "@(static|variable)/**/*.@(woff|woff2)"
> ```

Yes. That's correct. Please proceed like that.
