### ISSUE TITLE
Update: js-cookie is not updating. Latest version is 3.0.1

### ISSUE THREAD

**Issue by luislobo** [cdnjs/packages#979]
### Library name

js-cookie

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/j/js-cookie.json

### Library source

https://www.npmjs.com/package/js-cookie

### Files to include

- js.cookie.min.js
- js.cookie.js
- js.cookie.min.mjs
- js.cookie.mjs

One difference I found is that it changed the default branch from `master` to `main`

**Comment by luislobo** [comment]
Do you happen to know how much time does it take to be publicly available? 

It is still showing 
![image](https://user-images.githubusercontent.com/453120/152466929-4099242f-0e2f-48fc-8697-1c30f0656ef3.png)

Latest version is 3.0.1 on npmjs

**Comment by MattIPv4** [comment]
3.0.1 is now available: https://api.cdnjs.com/libraries/js-cookie/3.0.1
